### ISSUE TITLE
TheUnarchiver download address has changed

### ISSUE THREAD

**Issue by aysiu** [autopkg/recipes#106]
Running it now gives this error:

autopkg run -v TheUnarchiver.munki
Processing TheUnarchiver.munki...
TheUnarchiverURLProvider
Couldn't find The Unarchiver download URL in http://unarchiver.c3.cx/unarchiver
Failed.

It looks as if the new download address is
http://unarchiver.c3.cx/downloads/TheUnarchiver3.9.1.zip

**Comment by gregneagle** [comment]
Fixing this will require a re-do of TheUnarchiverURLProvider.py, or possibly a switch to URLTextSearcher in the .download recipe. Possibly also a new option should be added to control whether one downloads the "Mac App Store" version or the "Legacy" version as explained here under "Other Links": http://unarchiver.c3.cx/unarchiver

A Pull Request would be appreciated!

**Comment by aysiu** [comment]
I'm a bit of a GitHub novice, so I'm embarrassed to say I don't know properly how to do a pull request (even after reading tutorials), but if I can get a working fork of the download recipe, maybe that might be easy to merge in? Let me see what I can do.

**Comment by aysiu** [comment]
Thanks, jessepeterson
