### ISSUE TITLE
Silverlight.pkg recipe is erroring on Versioner processor

### ISSUE THREAD

**Issue by rtrouton** [autopkg/recipes#108]
I'm seeing an error when running the following recipe:

`com.github.autopkg.pkg.Silverlight`

Please see below for the output:

computername:~ username$ autopkg run com.github.autopkg.pkg.Silverlight -vvv
Processing com.github.autopkg.pkg.Silverlight...
{'AUTOPKG_VERSION': u'0.5.0',
 u'DOWNLOAD_URL': u'http://www.microsoft.com/getsilverlight/handlers/getsilverlight.ashx',
 u'NAME': u'Silverlight',
 'PARENT_RECIPES': [u'/Users/username/Library/AutoPkg/RecipeRepos/com.github.autopkg.recipes/Silverlight/Silverlight.download.recipe'],
 'RECIPE_CACHE_DIR': u'/Users/username/Library/AutoPkg/Cache/com.github.autopkg.pkg.Silverlight',
 'RECIPE_DIR': u'/Users/username/Library/AutoPkg/RecipeRepos/com.github.autopkg.recipes/Silverlight',
 'RECIPE_OVERRIDE_DIRS': ['~/Library/AutoPkg/RecipeOverrides'],
 'RECIPE_PATH': u'/Users/username/Library/AutoPkg/RecipeRepos/com.github.autopkg.recipes/Silverlight/Silverlight.pkg.recipe',
 u'RECIPE_REPOS': {u'/Users/username/Library/AutoPkg/RecipeRepos/com.github.autopkg.arubdesu-recipes': {
    URL = "https://github.com/autopkg/arubdesu-recipes";
},
                   u'/Users/username/Library/AutoPkg/RecipeRepos/com.github.autopkg.gerardkok-recipes': {
    URL = "https://github.com/autopkg/gerardkok-recipes";
},
                   u'/Users/username/Library/AutoPkg/RecipeRepos/com.github.autopkg.golbiga-recipes': {
    URL = "https://github.com/autopkg/golbiga-recipes";
},
                   u'/Users/username/Library/AutoPkg/RecipeRepos/com.github.autopkg.hansen-m-recipes': {
    URL = "https://github.com/autopkg/hansen-m-recipes";
},
                   u'/Users/username/Library/AutoPkg/RecipeRepos/com.github.autopkg.hjuutilainen-recipes': {
    URL = "https://github.com/autopkg/hjuutilainen-recipes";
},
                   u'/Users/username/Library/AutoPkg/RecipeRepos/com.github.autopkg.homebysix-recipes': {
    URL = "https://github.com/autopkg/homebysix-recipes";
},
                   u'/Users/username/Library/AutoPkg/RecipeRepos/com.github.autopkg.jps3-recipes': {
    URL = "https://github.com/autopkg/jps3-recipes";
},
                   u'/Users/username/Library/AutoPkg/RecipeRepos/com.github.autopkg.justinrummel-recipes': {
    URL = "https://github.com/autopkg/justinrummel-recipes";
},
                   u'/Users/username/Library/AutoPkg/RecipeRepos/com.github.autopkg.recipes': {
    URL = "https://github.com/autopkg/recipes";
},
                   u'/Users/username/Library/AutoPkg/RecipeRepos/com.github.autopkg.rtrouton-recipes': {
    URL = "https://github.com/autopkg/rtrouton-recipes";
},
                   u'/Users/username/Library/AutoPkg/RecipeRepos/com.github.autopkg.scriptingosx-recipes': {
    URL = "https://github.com/autopkg/scriptingosx-recipes";
},
                   u'/Users/username/Library/AutoPkg/RecipeRepos/com.github.autopkg.sheagcraig-recipes': {
    URL = "https://github.com/autopkg/sheagcraig-recipes";
}},
 u'RECIPE_SEARCH_DIRS': [u'.',
                         u'~/Library/AutoPkg/Recipes',
                         u'/Library/AutoPkg/Recipes',
                         u'/Users/username/Library/AutoPkg/RecipeRepos/com.github.autopkg.hjuutilainen-recipes',
                         u'/Users/username/Library/AutoPkg/RecipeRepos/com.github.autopkg.gerardkok-recipes',
                         u'/Users/username/Library/AutoPkg/RecipeRepos/com.github.autopkg.rtrouton-recipes',
                         u'/Users/username/Library/AutoPkg/RecipeRepos/com.github.autopkg.recipes',
                         u'/Users/username/Library/AutoPkg/RecipeRepos/com.github.autopkg.scriptingosx-recipes',
                         u'/Users/username/Library/AutoPkg/RecipeRepos/com.github.autopkg.sheagcraig-recipes',
                         u'/Users/username/Library/AutoPkg/RecipeRepos/com.github.autopkg.hansen-m-recipes',
                         u'/Users/username/Library/AutoPkg/RecipeRepos/com.github.autopkg.homebysix-recipes',
                         u'/Users/username/Library/AutoPkg/RecipeRepos/com.github.autopkg.golbiga-recipes',
                         u'/Users/username/Library/AutoPkg/RecipeRepos/com.github.autopkg.arubdesu-recipes',
                         u'/Users/username/Library/AutoPkg/RecipeRepos/com.github.autopkg.jps3-recipes',
                         u'/Users/username/Library/AutoPkg/RecipeRepos/com.github.autopkg.justinrummel-recipes',
                         u'/Users/username/Library/AutoPkg/RecipeRepos/com.github.autopkg.recipes/Silverlight'],
 u'USER_AGENT': u'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_3) AppleWebKit/536.28.10 (KHTML, like Gecko) Version/6.0.3 Safari/536.28.10',
 'verbose': 3}
URLDownloader
{'Input': {'filename': u'Silverlight.dmg',
           'request_headers': {
    "user-agent" = "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_3) AppleWebKit/536.28.10 (KHTML, like Gecko) Version/6.0.3 Safari/536.28.10";
},
           'url': u'http://www.microsoft.com/getsilverlight/handlers/getsilverlight.ashx'}}
URLDownloader: Item at URL is unchanged.
URLDownloader: Using existing /Users/username/Library/AutoPkg/Cache/com.github.autopkg.pkg.Silverlight/downloads/Silverlight.dmg
{'Output': {'pathname': u'/Users/username/Library/AutoPkg/Cache/com.github.autopkg.pkg.Silverlight/downloads/Silverlight.dmg'}}
EndOfCheckPhase
{'Input': {}}
{'Output': {}}
FlatPkgUnpacker
{'Input': {'destination_path': u'/Users/username/Library/AutoPkg/Cache/com.github.autopkg.pkg.Silverlight/expand',
           'flat_pkg_path': u'/Users/username/Library/AutoPkg/Cache/com.github.autopkg.pkg.Silverlight/downloads/Silverlight.dmg/Silverlight.pkg'}}
FlatPkgUnpacker: Mounted disk image /Users/username/Library/AutoPkg/Cache/com.github.autopkg.pkg.Silverlight/downloads/Silverlight.dmg
FlatPkgUnpacker: Unpacked /private/tmp/dmg.5XvyvF/Silverlight.pkg to /Users/username/Library/AutoPkg/Cache/com.github.autopkg.pkg.Silverlight/expand
{'Output': {}}
PkgPayloadUnpacker
{'Input': {'destination_path': u'/Users/username/Library/AutoPkg/Cache/com.github.autopkg.pkg.Silverlight/unpack',
           'pkg_payload_path': u'/Users/username/Library/AutoPkg/Cache/com.github.autopkg.pkg.Silverlight/expand/silverlight_plugin.pkg/Payload'}}
PkgPayloadUnpacker: Unpacked /Users/username/Library/AutoPkg/Cache/com.github.autopkg.pkg.Silverlight/expand/silverlight_plugin.pkg/Payload to /Users/username/Library/AutoPkg/Cache/com.github.autopkg.pkg.Silverlight/unpack
{'Output': {}}
Versioner
{'Input': {'input_plist_path': u'/Users/username/Library/AutoPkg/Cache/com.github.autopkg.pkg.Silverlight/unpack/Library/Internet Plug-Ins/Silverlight.plugin/Contents/Info.plist',
           'plist_version_key': u'CFBundleVersion'}}
File '/Users/username/Library/AutoPkg/Cache/com.github.autopkg.pkg.Silverlight/unpack/Library/Internet Plug-Ins/Silverlight.plugin/Contents/Info.plist' does not exist or could not be read.
Failed.
Receipt written to /Users/username/Library/AutoPkg/Cache/com.github.autopkg.pkg.Silverlight/receipts/com.github.autopkg.pkg-receipt-20150902-081312.plist

The following recipes failed:
    com.github.autopkg.pkg.Silverlight
        Error in com.github.autopkg.pkg.Silverlight: Processor: Versioner: Error: File '/Users/username/Library/AutoPkg/Cache/com.github.autopkg.pkg.Silverlight/unpack/Library/Internet Plug-Ins/Silverlight.plugin/Contents/Info.plist' does not exist or could not be read.

Nothing downloaded, packaged or imported.
computername:~ username$

**Comment by gregneagle** [comment]
Addressed here https://github.com/autopkg/recipes/commit/d8bd02c03edc04b21507a47b896826127aa099e0

Pkg payload has a new install-location, so the expected expanded path did not exist.

**Comment by Daz-wallace** [comment]
Just ran this recipe (8th September 2015) with OS X 10.10.5 and it pulled down silverlight v5.1.40728.0 and it appears to have added the Library directory back in to the install path?

Please confirm but it appears that the change may need to be reverted.

**Comment by timsutton** [comment]
The Silverlight downloads page for me also downloads 5.1.40728.0, so perhaps MS have pulled the later version.

![screenshot 2015-09-08 08 48 47](https://cloud.githubusercontent.com/assets/119358/9735122/6f26a3ec-5606-11e5-8986-e2cf2a458be4.png)

If we revert this we'll probably need to re-apply the change again when the next version is released. Since this seems to have just happened hours ago, perhaps let's give this some time today and see if it settles.

**Comment by Daz-wallace** [comment]
No problem. I can always work around it for now.

Thanks for the reply!

**Comment by timsutton** [comment]
..and a newer version has been released: `Silverlight-5.1.40904.0.pkg`
