### ISSUE TITLE
Java 8 UpDate 60 Version 27

### ISSUE THREAD

**Issue by KrymzonAshe** [autopkg/recipes#111]
Hello Tim,

I am running into this issue with Autopkg and the latest flavor of Java. Below is the output:

Currently Running Autopkg 0.5.1, Git 1.9.5, Munki 2.2.4, and Autopkgr 1.3.1. It seems as though the recipe needs to be updated. But after I updated the Autopkg Repo and recipes, I still get the same issue. Thanks!

~ admin$ autopkg run -v OracleJava8.munki
Processing OracleJava8.munki...
URLTextSearcher
URLTextSearcher: Found matching text (url): http://download.oracle.com/otn-pub/java/jdk/8u60-b27/jre-8u60-macosx-x64.dmg
URLTextSearcher: Found matching text (match): http://download.oracle.com/otn-pub/java/jdk/8u60-b27/jre-8u60-macosx-x64.dmg
URLDownloader
URLDownloader: Item at URL is unchanged.
URLDownloader: Using existing /Users/admin/Library/AutoPkg/Cache/com.github.autopkg.munki.OracleJava8/downloads/OracleJava8.dmg
EndOfCheckPhase
CodeSignatureVerifier
CodeSignatureVerifier: hdiutil imageinfo error hdiutil: imageinfo failed - image not recognized
 with image /Users/admin/Library/AutoPkg/Cache/com.github.autopkg.munki.OracleJava8/downloads/OracleJava8.dmg.
/Users/admin/Library/AutoPkg/Cache/com.github.autopkg.munki.OracleJava8/downloads/OracleJava8.dmg is not mounted
Failed.
Receipt written to /Users/admin/Library/AutoPkg/Cache/com.github.autopkg.munki.OracleJava8/receipts/OracleJava8-receipt-20150908-122158.plist

The following recipes failed:
    OracleJava8.munki
        Error in com.github.autopkg.munki.OracleJava8: Processor: CodeSignatureVerifier: Error: /Users/admin/Library/AutoPkg/Cache/com.github.autopkg.munki.OracleJava8/downloads/OracleJava8.dmg is not mounted

Nothing downloaded, packaged or imported.

**Comment by timsutton** [comment]
These lines suggest there might be an issue with the DMG you've downloaded:

```
URLDownloader: Item at URL is unchanged.
URLDownloader: Using existing /Users/admin/Library/AutoPkg/Cache/com.github.autopkg.munki.OracleJava8/downloads/OracleJava8.dmg
EndOfCheckPhase
CodeSignatureVerifier
CodeSignatureVerifier: hdiutil imageinfo error hdiutil: imageinfo failed - image not recognized
with image /Users/admin/Library/AutoPkg/Cache/com.github.autopkg.munki.OracleJava8/downloads/OracleJava8.dmg.
```

I'd suggest removing `/Users/admin/Library/AutoPkg/Cache/com.github.autopkg.munki.OracleJava8/downloads/OracleJava8.dmg` and re-running the recipe.

**Comment by KrymzonAshe** [comment]
Thanks Tim,

Odd though I didn't have to delete from version 8 Update 45 to 8 Update 51... I presume Java may had changed something?

In any event thanks. Now I know if I run into that issue again with anything. I'll just delete the DMG first and attempt that.
