### ISSUE TITLE
MSExcel2016 recipe fails to verify package

### ISSUE THREAD

**Issue by hymmm** [autopkg/recipes#117]
MSExcel2016 recipe fails to verify package as below

> CodeSignatureVerifier
> {'Input': {'expected_authority_names': (
>     "Developer ID Installer: Microsoft Corporation (UBF8T346G9)",
>     "Developer ID Certification Authority",
>     "Apple Root CA"
> ),
>            'input_path': u'/Users/Administrator/Library/AutoPkg/Cache/com.github.autopkg.munki.MSExcel2016/downloads/MSExcel2016-15.14.0.pkg'}}
> CodeSignatureVerifier: Verifying installer package signature...
> CodeSignatureVerifier: Package "MSExcel2016-15.14.0.pkg":
> CodeSignatureVerifier:    Status: package is invalid (checksum did not verify)
> Code signature verification failed. Note that all verification can be disabled by setting the variable DISABLE_CODE_SIGNATURE_VERIFICATION to a non-empty value.
> Failed.
> Receipt written to /Users/Administrator/Library/AutoPkg/Cache/com.github.autopkg.munki.MSExcel2016/receipts/MSExcel2016.munki-receipt-20151007-181545.plist
> 
> The following recipes failed:

**Comment by timsutton** [comment]
I'm not seeing that here:

```
CodeSignatureVerifier
CodeSignatureVerifier: Verifying installer package signature...
CodeSignatureVerifier: Package "MSExcel2016-15.14.0.pkg":
CodeSignatureVerifier:    Status: signed by a certificate trusted by Mac OS X
CodeSignatureVerifier:    Certificate Chain:
CodeSignatureVerifier:     1. Developer ID Installer: Microsoft Corporation (UBF8T346G9)
CodeSignatureVerifier:        SHA1 fingerprint: 9B 6B 91 3B B1 3F 68 26 12 20 EC 72 11 F0 F2 0E 92 E4 B1 EB
CodeSignatureVerifier:        -----------------------------------------------------------------------------
CodeSignatureVerifier:     2. Developer ID Certification Authority
CodeSignatureVerifier:        SHA1 fingerprint: 3B 16 6C 3B 7D C4 B7 51 C9 FE 2A FA B9 13 56 41 E3 88 E1 86
CodeSignatureVerifier:        -----------------------------------------------------------------------------
CodeSignatureVerifier:     3. Apple Root CA
CodeSignatureVerifier:        SHA1 fingerprint: 61 1E 5B 66 2C 59 3A 08 FF 58 D1 4A E2 24 52 D1 98 DF 6C 60
CodeSignatureVerifier: 
CodeSignatureVerifier: Signature is valid
CodeSignatureVerifier: Authority name chain is valid
```

Are you sure that the package you downloaded may have been interrupted or somehow corrupt? You can try removing the download at: `/Users/Administrator/Library/AutoPkg/Cache/com.github.autopkg.munki.MSExcel2016/downloads/MSExcel2016-15.14.0.pkg` and then re-trying. The output from pkgutil ("package is invalid (checksum did not verify)" would suggest to me that there was something invalid in the package integrity check.

**Comment by hymmm** [comment]
Thanks!
You're right, package is corrupted. (I should check it before asking, sorry)
