### ISSUE TITLE
mozillaURLprovider.py 404 error

### ISSUE THREAD

**Issue by karlmikaelskar** [autopkg/recipes#119]
Hi!

When downloading Firefox I get a 404 error. I think the problem is the download url might have been changed from
http://ftp.mozilla.org/pub/mozilla.org/
to
http://ftp.mozilla.org/pub/

Thanks for the great work!

regards

Mikael Johansson

**Comment by timsutton** [comment]
Thanks, but unfortunately it's not going to (currently) return the most recent release (see #118).

**Comment by ih84ds** [comment]
I just submitted a PR to fix these issues. Seemed to Work For Me.

**Comment by timsutton** [comment]
Closed in #120.
