### ISSUE TITLE
Can't open URL http://unarchiver.c3.cx/updates.rss

### ISSUE THREAD

**Issue by portalpie** [autopkg/recipes#122]
This is my first ever issue submission so please school me if I should be providing more info etc.

Error in com.github.autopkg.munki.TheUnarchiver: Processor: SparkleUpdateInfoProvider: Error: Can't open URL http://unarchiver.c3.cx/updates.rss

Thanks
Morgs

**Comment by timsutton** [comment]
Thanks!

**Comment by portalpie** [comment]
Most welcome. Thank you for all of your hard work.
