### ISSUE TITLE
TheUnarchiver ditto failed: ditto: Couldn't read PKZip signature

### ISSUE THREAD

**Issue by portalpie** [autopkg/recipes#125]
Hopefully this helps...

Message:
Error in com.github.autopkg.munki.TheUnarchiver: Processor: Unarchiver: Error: Unarchiving /Users/sc_admin/Library/AutoPkg/Cache/com.github.autopkg.munki.TheUnarchiver/downloads/TheUnarchiver3.10.1.zip with ditto failed: ditto: Couldn't read PKZip signature

Traceback:
Traceback (most recent call last): File "/usr/local/bin/autopkg", line 1459, in run_recipes autopackager.process(recipe) File "/Library/AutoPkg/autopkglib/__init__.py", line 479, in process % (identifier, step["Processor"], unicode(err))) AutoPackagerError: Error in com.github.autopkg.munki.TheUnarchiver: Processor: Unarchiver: Error: Unarchiving /Users/sc_admin/Library/AutoPkg/Cache/com.github.autopkg.munki.TheUnarchiver/downloads/TheUnarchiver3.10.1.zip with ditto failed: ditto: Couldn't read PKZip signature

Thank You

**Comment by gregneagle** [comment]
Works as expected here:

```
% autopkg run TheUnarchiver.munki
Processing TheUnarchiver.munki...

The following new items were imported into Munki:
    Name           Version  Catalogs  Pkginfo Path                     Pkg Repo Path                  
    ----           -------  --------  ------------                     -------------                  
    TheUnarchiver  3.10.1   testing   apps/TheUnarchiver-3.10.1.plist  apps/TheUnarchiver-3.10.1.dmg  

The following new items were downloaded:
    Download Path                                                                                                  
    -------------                                                                                                  
    /Users/gneagle/Library/AutoPkg/Cache/com.github.autopkg.munki.TheUnarchiver/downloads/TheUnarchiver3.10.1.zip  
```

Perhaps a corrupted download on your end? Try removing the downloaded zip and running the recipe again.

**Comment by timsutton** [comment]
There's a bug in recent versions of curl for which a workaround was recently fixed in AutoPkg: https://github.com/autopkg/autopkg/pull/237 - so this recipe probably won't work reliably unless you're running the current Git master of AutoPkg or running the recipe on an older OS.

It will still work if you first clear your cache or the downloaded item for this recipe, it's the subsequent runs that expose the curl bug. The Unarchiver is updated very rarely, though - 3.10.1 is the only release since July 2014.

I'll add a note to this recipe about its current status.

**Comment by gregneagle** [comment]
It's not clear this is a bug in curl; but it's definitely an issue with older versions of the CURLDownloader.

**Comment by timsutton** [comment]
I just remember that right after I made a change to TheUnarchiver recipes to switch to CURLDownloader (for an SSL workaround), @hjuutilainen seemed to have this recipe surface that issue.

**Comment by hjuutilainen** [comment]
Yep, that's my recollection too: SSL trouble -> CURLDownloader -> Mystical problems after the second AutoPkg run until I did a `ls -la` and found the zero byte file when the download is not modified.

**Comment by portalpie** [comment]
You guys were right. Removing the zip and re-running the recipe was the fix. Thank you.
