### ISSUE TITLE
DropBox testing build

### ISSUE THREAD

**Issue by nescom-it** [autopkg/recipes#126]
Is there a way to set which build you want? Currently this recipe appears to be getting its updates from the testing build instead of the stable build according to the release notes. Latest testing build is 3.12.4 and the latest stable build 3.10.11
https://www.dropbox.com/release_notes

**Comment by timsutton** [comment]
There isn't currently, but I also don't recommend people push out Dropbox updates via Munki at all, for reasons described in the Dropbox.munki description.

**Comment by nescom-it** [comment]
That makes sense. Thanks you for your help.
