### ISSUE TITLE
Firefox.munki.recipe - 404

### ISSUE THREAD

**Issue by RicknTx** [autopkg/recipes#129]
It appears Mozilla might have changed the download repo for Firefox... Haven't been able to pull since version 41.  Current release is 43.

Here's the output when I try to run the job:

/bin/sh -xe /Users/Shared/Jenkins/tmp/hudson7662008801168762750.sh
+ /usr/local/bin/autopkg run Firefox.munki.recipe
Can't download http://ftp.mozilla.org/pub/mozilla.org/firefox/releases/latest/mac/en-US: HTTP Error 404: Not Found
Failed.
Processing Firefox.munki.recipe...

The following recipes failed:
    Firefox.munki.recipe
        Error in com.github.autopkg.munki.firefox-rc-en_US: Processor: MozillaURLProvider: Error: Can't download http://ftp.mozilla.org/pub/mozilla.org/firefox/releases/latest/mac/en-US: HTTP Error 404: Not Found

**Comment by timsutton** [comment]
Release 41 is around when Mozilla changed their methodology to download releases, and the recipes were updated to suit. Is your `recipes` repo up to date?

**Comment by RicknTx** [comment]
Hi Tim,
I had run the repo-update prior to filing, but something must have hung up or something.  I did notice that one of the repos is prompting for credentials...  

Attempting git pull for /Users/Shared/Jenkins/Library/AutoPkg/RecipeRepos/com.github.keeleysam.recipes...
Username: 
Password: 
ERROR: error: The requested URL returned error: 403 while accessing http://github.com/keeleysam/recipes/info/refs


I've never seen that before, but Firefox is updating now.

**Comment by timsutton** [comment]
AutoPkg blindly does a `git pull` on its recipe repos, so you can check yourself by running git from within the directory of the repo clone. Errors can happen if you've switched branches or changed the upstream remote.

**Comment by timsutton** [comment]
Closing as the issue with Firefox was fixed with a recent Mozilla recipes update.
