### ISSUE TITLE
OracleJava8.munki.recipe - Errors

### ISSUE THREAD

**Issue by RicknTx** [autopkg/recipes#130]
When I try to run the OracleJava8 recipe it is erring..

Is there something I can do to fix it by chance?  

+ /usr/local/bin/autopkg run OracleJava8.munki.recipe
Invalid input path
Failed.
Processing OracleJava8.munki.recipe...

The following recipes failed:
    OracleJava8.munki.recipe
        Error in com.github.autopkg.munki.OracleJava8: Processor: CodeSignatureVerifier: Error: Invalid input path

**Comment by timsutton** [comment]
Working ok here. Have you tried clearing your cache and re-running the recipe in case the download was corrupt?

**Comment by RicknTx** [comment]
Clearing the cache seems to have fixed it there.  It gave an input error initially, but it appears to be working well now.  Thanks!
