### ISSUE TITLE
OracleJava8 recipe problem with path, Oracle changed their mind again

### ISSUE THREAD

**Issue by rrenstrom** [autopkg/recipes#135]
Seems this change https://github.com/autopkg/recipes/commit/0678971bf0d648f853748fded888653354173ef2 needs to be reverted to previous, since Oracle is distributing the app instead of pkg in the disk image.

$ autopkg run -v OracleJava8.munki
Processing OracleJava8.munki...
URLTextSearcher
URLTextSearcher: Found matching text (url): http://download.oracle.com/otn-pub/java/jdk/8u71-b15/jre-8u71-macosx-x64.dmg
URLTextSearcher: Found matching text (match): http://download.oracle.com/otn-pub/java/jdk/8u71-b15/jre-8u71-macosx-x64.dmg
URLDownloader
URLDownloader: Storing new Last-Modified header: Tue, 26 Jan 2016 18:59:09 GMT
URLDownloader: Storing new ETag header: "b5f3a766407a7bb64995a7d900095f68:1453842424"
URLDownloader: Downloaded /Users/robr/Library/AutoPkg/Cache/com.github.autopkg.munki.OracleJava8/downloads/OracleJava8.dmg
EndOfCheckPhase
CodeSignatureVerifier
CodeSignatureVerifier: Mounted disk image /Users/robr/Library/AutoPkg/Cache/com.github.autopkg.munki.OracleJava8/downloads/OracleJava8.dmg
CodeSignatureVerifier: Invalid input path: /Users/robr/Library/AutoPkg/Cache/com.github.autopkg.munki.OracleJava8/downloads/OracleJava8.dmg/Java 8 Update*.pkg
Invalid input path
Failed.
Receipt written to /Users/robr/Library/AutoPkg/Cache/com.github.autopkg.munki.OracleJava8/receipts/OracleJava8-receipt-20160127-155638.plist

The following recipes failed:
    OracleJava8.munki
        Error in com.github.autopkg.munki.OracleJava8: Processor: CodeSignatureVerifier: Error: Invalid input path

**Comment by seansgm** [comment]
Tim updated this 9 days ago.

0678971
<https://github.com/autopkg/recipes/commit/0678971bf0d648f853748fded888653354173ef2#diff-1e1bb879694fe46c9809d784ece79bee>

You probably need to update your repo.

Sean

**Comment by timsutton** [comment]
Yes, though @rrenstrom referred to the same commit and suggested _that_ be reverted. Can you please confirm if you're running on the latest master of the repo (`autopkg repo-update recipes`)?

The recipe is currently working OK here.

**Comment by seansgm** [comment]
Sorry, yeah, didn't spot that.  What overrides are you running?  You appear
to have OracleJava8dmg as the name of the dmg instead of OracleJava8.dmg.
So it looks like the name of the dmg is the same name as the mount point
path that the CodeSignatureVerifier process is being told to use to find
the pkg.

**Comment by rrenstrom** [comment]
@timsutton Correct, I'm saying the recipe change 9 days ago didn't work, since the dmg download I got from Oracle contained an app, not a pkg. I had the latest recipe and no overrides, and deleted previous dmg from downloads cache to force it to download again.

However, I just tried it again, and it worked. No change to recipe from yesterday.

$ autopkg repo-update all
...
Attempting git pull for /Users/robr/Library/AutoPkg/RecipeRepos/com.github.autopkg.recipes...
Already up-to-date.

But this time it downloaded a pkg instead of an app. Since the URL is the same today as it was yesterday,  I can only assume that the download file is changing on the Oracle server (or they have multiple servers, and some are returning a different dmg). Note the differences in Last-Modified header, and image CRC32...

Today's run, downloaded dmg with PKG:

URLTextSearcher: Found matching text (match): http://download.oracle.com/otn-pub/java/jdk/8u71-b15/jre-8u71-macosx-x64.dmg
URLDownloader
URLDownloader: Storing new Last-Modified header: Fri, 15 Jan 2016 16:45:32 GMT
URLDownloader: Storing new ETag header: "3ab972cf81b5feca03e911de94b0c0ee:1452881597"
URLDownloader: Downloaded /Users/robr/Library/AutoPkg/Cache/com.github.autopkg.munki.OracleJava8/downloads/OracleJava8.dmg


$ hdiutil attach /Users/robr/Library/AutoPkg/Cache/com.github.autopkg.munki.OracleJava8/downloads/OracleJava8.dmg  
expected   CRC32 $89AA7B8C
/dev/disk2          	GUID_partition_scheme          	
/dev/disk2s1        	Apple_HFS                      	/Volumes/Java 8 Update 71

$ ls -l /Volumes/Java\ 8\ Update\ 71/
total 123704
-rwxr-xr-x  1 robr  staff  63333284 Dec 22 15:44 Java 8 Update 71.pkg



Yesterday's run, downloaded dmg with APP:

URLTextSearcher: Found matching text (match): http://download.oracle.com/otn-pub/java/jdk/8u71-b15/jre-8u71-macosx-x64.dmg
URLDownloader
URLDownloader: Storing new Last-Modified header: Tue, 26 Jan 2016 18:59:09 GMT
URLDownloader: Storing new ETag header: "b5f3a766407a7bb64995a7d900095f68:1453842424"
URLDownloader: Downloaded /Users/robr/Library/AutoPkg/Cache/com.github.autopkg.munki.OracleJava8/downloads/OracleJava8.dmg


$ hdiutil attach /Users/robr/Library/AutoPkg/Cache/com.github.autopkg.munki.OracleJava8/downloads/OracleJava8.dmg  
expected   CRC32 $9BA6E799
/dev/disk2          	GUID_partition_scheme          	
/dev/disk2s1        	Apple_HFS                      	/Volumes/Java 8 Update 71


$ ls -l /Volumes/Java\ 8\ Update\ 71/"Java 8 Update"*.app/Contents/Resources/JavaAppletPlugin.pkg
-rwxr-xr-x  1 robr  staff  63333284 Dec 22 15:44 /Volumes/Java 8 Update 71/Java 8 Update 71.app/Contents/Resources/JavaAppletPlugin.pkg

**Comment by yagmot** [comment]
I'm seeing the same thing. As of java 8u72 it's back in app format. The current recipe gives me an "invalid input path" error.

**Comment by gregneagle** [comment]
I'm not sure how we can expect the recipe to handle seemingly-random results from a given URL.

**Comment by seansgm** [comment]
*sigh*

ls -1 /Volumes/Java\ 8\ Update\ 73/Java\ 8\ Update\
73.app/Contents/Resources/JavaAppletPlugin.pkg

/Volumes/Java 8 Update 73/Java 8 Update
73.app/Contents/Resources/JavaAppletPlugin.pkg

$ ls -1 /Volumes/Java\ 8\ Update\ 74/Java\ 8\ Update\
74.app/Contents/Resources/JavaAppletPlugin.pkg

/Volumes/Java 8 Update 74/Java 8 Update
74.app/Contents/Resources/JavaAppletPlugin.pkg


Did autopkg download a non app version for anyone?


Lucky Devs get a pkg


$ ls -1 /Volumes/JDK\ 8\ Update\ 73/

JDK 8 Update 73.pkg

$ ls -1 /Volumes/JDK\ 8\ Update\ 74/

JDK 8 Update 74.pkg

**Comment by timsutton** [comment]
I'm going to close this as the recipe's working with the current Oracle JRE version.

**Comment by seansgm** [comment]
The latest u73 and u74 just downloaded an app and not a pkg and so failed, whilst u71 and u72 (for me) downloaded a pkg.  Hence my question, has anyone received a non-app version of 73 or 74?

Are you saying that U73 for you downloaded a pkg?

**Comment by timsutton** [comment]
When it failed, were you running the latest version of the recipe? We've updated this recipe at least four times to account for Oracle changing its mind about the app vs. pkg nearly every release.

**Comment by seansgm** [comment]
Sorry, no I hadn't noticed the update.  Got the impression you weren't
going to change it back due to mixed response and as I hadn't seen any
further response I admit I didn't check.  Should have though!
