### ISSUE TITLE
Firefox URL

### ISSUE THREAD

**Issue by rvdmast** [autopkg/recipes#136]
Firefox recipe don't work:
Error in com.github.autopkg.munki.firefox-rc-en_US: Processor: MozillaURLProvider: Error: Can't download http://ftp.mozilla.org/pub/mozilla.org//firefox/releases/latest/mac/en-US: HTTP Error 404: Not Found

On http://ftp.mozilla.org/pub/firefox/releases/latest/ there's a readme that says:

_Please use download.mozilla.org to retrieve the latest Firefox release. 

For example, if you wish to download the US English installer for Windows (32bit)
the url is
   https://download.mozilla.org/?product=firefox-latest&os=win&lang=en-US_

**Comment by gregneagle** [comment]
I don't think you have the current Firefox recipes. Try running `autopkg repo-update recipes`

Current recipes download from a URL based on `"https://download.mozilla.org/?product=%s-%s&os=osx&lang=%s"`.
