### ISSUE TITLE
AdobeReaderUpdatesURLProvider: Output the version number?

### ISSUE THREAD

**Issue by mihelm** [autopkg/recipes#145]
Hi

This is mostly a feature request: In AdobeReaderUpdatesURLProvider.py, could you add the line

self.output("Found Version %s" % self.env["version"])

below line 148, so the processor returns the version number of the update it finds?

Thanks!

Cheers, michael.

**Comment by timsutton** [comment]
You'd like that added so that it just outputs it to the console on verbose runs? Looks like you know how to do it already, so you would you like to submit this as a PR?

**Comment by mihelm** [comment]
Erm... Actually, never mind.

I was having difficulty getting a downstream recipe to use version and didn't realise AdobeReaderUpdatesURLProvider was returning version quietly. Let's just say I just learned a few things. :-P

I'll submit this cosmetic change in a few weeks when I'm more comfortable interacting with other people's repos.

In the meantime I'll close this issue since it's more of a non-issue. ;-)

Cheers, michael.

**Comment by gregneagle** [comment]
You can run `autopkg` with increasing levels of verbiage with -v and -vv. You would have seen the version in the output then...

**Comment by mihelm** [comment]
Thanks for the tip, that's really handy! :-D
