### ISSUE TITLE
SassafrasK2Client.munki URL Parameter Still calling 72

### ISSUE THREAD

**Issue by BaddMann** [autopkg/recipes#149]
I've been unable to update our K2 client past 72.

Couldn't understand why. 
The Download Recipe is fixed and is asking for 73.
I created my override some time ago, is this maybe why it's not updating to 73?

Why is the munki recipe asking for the download URL?
Shouldn't that be handled by the download recipe?

**Comment by BaddMann** [comment]
The URL is still hard coded as 72.... 
Not sure what that's about, but I just found my OVERRIDE was listing REVISION 72.

**Comment by timsutton** [comment]
That's to be expected. When you override a recipe, _all_ Input keys are copied into your override, which will remain for as long as you keep them there. Alternatively you may choose to remove some if you'd prefer to always take the recipe's "default" provided values. For more info, see:

https://github.com/autopkg/autopkg/wiki/Recipe-Overrides#input-keys-and-merging
