### ISSUE TITLE
Adium is failing with an SSL Certificate issue

### ISSUE THREAD

**Issue by RicknTx** [autopkg/recipes#157]
When trying to run autopkg on Adium.munki.recipe it is failing with an SSL cert issue.

```
+ /usr/local/bin/autopkg run Adium.munki.recipe
Could not retrieve URL https://adium.im:   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                Dload  Upload   Total   Spent    Left  Speed

 0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
 0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (60) SSL certificate problem: Invalid certificate chain
More details here: http://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
of Certificate Authority (CA) public keys (CA certs). If the default
bundle file isn't adequate, you can specify an alternate file
using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
the bundle, the certificate verification probably failed due to a
problem with the certificate (it might be expired, or the name might
not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
the -k (or --insecure) option.

```

Has anyone experienced this before?  Is there something incorrect on my end perhaps?

Thank you in advance

**Comment by timsutton** [comment]
Nothing wrong on your end - Adium's certificate for `adium.im` has expired:

<img width="458" alt="screenshot 2016-07-02 12 15 47" src="https://cloud.githubusercontent.com/assets/119358/16541365/ba24fcc6-404e-11e6-9261-3c7edd2531bb.png">

**Comment by uberjay** [comment]
Still expired... 61 days ago. Anyone know who handles infrastructure business? Seems like either the person who's responsible doesn't know, or doesn't exist anymore.

**Comment by timsutton** [comment]
What about just pulling the Adium recipes? It's almost never updated and is trivial to do manually at their average rate of one release a year.

https://trac.adium.im/wiki/AdiumVersionHistory

**Comment by timsutton** [comment]
Their cert was recently renewed, I believe in part thanks to prodding by @fuzzylogiq:

<img width="460" alt="screenshot 2016-08-31 15 53 17" src="https://cloud.githubusercontent.com/assets/119358/18144124/0ee0ddca-6f93-11e6-8e42-726d8fe627a9.png">
