### ISSUE TITLE
Code signature verification on Google Chrome

### ISSUE THREAD

**Issue by aysiu** [autopkg/recipes#158]
I tried to add Google Chrome code signature verification to this recipe (to make a pull request):

```
<dict>
    <key>Processor</key>
    <string>CodeSignatureVerifier</string>
    <key>Arguments</key>
    <dict>
        <key>input_path</key>
        <string>%pathname%/Google Chrome.app</string>
        <key>requirement</key>
        <string>(identifier "com.google.Chrome" or identifier "com.google.Chrome.canary") and certificate leaf = H"85cee8254216185620ddc8851c7a9fc4dfe120ef"</string>
    </dict>
</dict>
```

But I get an error about it being obsolete:

```
CodeSignatureVerifier: /private/tmp/dmg.UGTSVx/Google Chrome.app: resource envelope is obsolete (custom omit rules)
Code signature verification failed. Note that all verifications can be disabled by setting the variable DISABLE_CODE_SIGNATURE_VERIFICATION to a non-empty value.
Failed.
```

That's even though it's supposedly using version 2:

```
Sealed Resources version=2 rules=7 files=202
```

Just in case I was doing it wrong, I happened to notice someone has a Canary AutoPkg recipe, so I tried that out, and it faced the same issue.

Recipe: https://github.com/smashism/autopkg/blob/master/ChromeCanary/Chrome.download.recipe#L39-49

Error:

```
CodeSignatureVerifier: Verifying application bundle signature...
CodeSignatureVerifier: /private/tmp/dmg.TRpbSc/Google Chrome Canary.app: resource envelope is obsolete (custom omit rules)
Code signature verification failed. Note that all verifications can be disabled by setting the variable DISABLE_CODE_SIGNATURE_VERIFICATION to a non-empty value.
Failed.
```

So is code signature verification not possible for Google Chrome, even though it's version 2?

**Comment by arubdesu** [comment]
Thanks for having captured this a bit ago, I'm now realizing the code sig verification option to do this compatible version of a check has been present for a good long while. About time we take a swing at addressing it.
