### ISSUE TITLE
Office 15.24 vs 15.25

### ISSUE THREAD

**Issue by majorsl** [autopkg/recipes#163]
Firstly, I'm not sure if this is a good place to ask this. I'm very sorry if it isn't.

I have two instances of autopkg (different servers, different locations) using the MSOffice updates recipe.

Server 1 received all of the updates for 15.25, no problem.  Server 2 got everything but Word and Outlook for some reason.  When I try to update Word, for example, (of course updating recipes first) it only finds 15.24:

autopkg run -v MSWord2016.munki
Processing MSWord2016.munki...
MSOffice2016URLandUpdateInfoProvider
MSOffice2016URLandUpdateInfoProvider: Found URL https://officecdn.microsoft.com/pr/C1297A47-86C4-4C1F-97FA-950631F94777/OfficeMac/Microsoft_Word_15.24.0_160709_Updater.pkg
MSOffice2016URLandUpdateInfoProvider: Got update: 'Microsoft Word Update 15.24.0'
MSOffice2016URLandUpdateInfoProvider: Extracting version 15.24.16070900 from metadata 'Update Version' key
MSOffice2016URLandUpdateInfoProvider: Extracting version 15.24.16070900 from metadata 'Update Version' key
MSOffice2016URLandUpdateInfoProvider: Additional pkginfo: {'installs': [{'path': u'/Applications/Microsoft Word.app', 'CFBundleVersion': '15.24.16070900', 'type': 'application'}], 'minimum_os_version': '10.10.0', 'description': '<html><p style="font-family:Helvetica;font-size:12px">For detailed information about this update, please visit the following Web site: </p>\n\n<p style="font-family:Helvetica;font-size:12px"><a href="https://go.microsoft.com/fwlink/?LinkID=808251" target="_blank">https://go.microsoft.com/fwlink/?LinkID=808251</a></p></html>'}
URLDownloader
URLDownloader: Item at URL is unchanged.
URLDownloader: Using existing /Users/administrator/Library/AutoPkg/Cache/com.github.autopkg.munki.MSWord2016/downloads/MSWord2016-15.24.16070900.pkg
EndOfCheckPhase
CodeSignatureVerifier
CodeSignatureVerifier: Verifying installer package signature...
CodeSignatureVerifier: Package "MSWord2016-15.24.16070900.pkg":
CodeSignatureVerifier:    Status: signed by a certificate trusted by Mac OS X
CodeSignatureVerifier:    Certificate Chain:
CodeSignatureVerifier:     1. Developer ID Installer: Microsoft Corporation (UBF8T346G9)
CodeSignatureVerifier:        SHA1 fingerprint: 9B 6B 91 3B B1 3F 68 26 12 20 EC 72 11 F0 F2 0E 92 E4 B1 EB
CodeSignatureVerifier:        -----------------------------------------------------------------------------
CodeSignatureVerifier:     2. Developer ID Certification Authority
CodeSignatureVerifier:        SHA1 fingerprint: 3B 16 6C 3B 7D C4 B7 51 C9 FE 2A FA B9 13 56 41 E3 88 E1 86
CodeSignatureVerifier:        -----------------------------------------------------------------------------
CodeSignatureVerifier:     3. Apple Root CA
CodeSignatureVerifier:        SHA1 fingerprint: 61 1E 5B 66 2C 59 3A 08 FF 58 D1 4A E2 24 52 D1 98 DF 6C 60
CodeSignatureVerifier: 
CodeSignatureVerifier: Signature is valid
CodeSignatureVerifier: Authority name chain is valid
MunkiPkginfoMerger
MunkiPkginfoMerger: Merged {'installs': [{'path': u'/Applications/Microsoft Word.app', 'CFBundleVersion': '15.24.16070900', 'type': 'application'}], 'minimum_os_version': '10.10.0', 'description': '<html><p style="font-family:Helvetica;font-size:12px">For detailed information about this update, please visit the following Web site: </p>\n\n<p style="font-family:Helvetica;font-size:12px"><a href="https://go.microsoft.com/fwlink/?LinkID=808251" target="_blank">https://go.microsoft.com/fwlink/?LinkID=808251</a></p></html>'} into pkginfo
MunkiImporter
MunkiImporter: Item MSWord2016-15.24.16070900.pkg already exists in the munki repo as pkgs/apps/MSWord2016-15.24.0-15.24.16070900.pkg.
Receipt written to /Users/administrator/Library/AutoPkg/Cache/com.github.autopkg.munki.MSWord2016/receipts/MSWord2016-receipt-20160826-123001.plist

Nothing downloaded, packaged or imported.

**Comment by timsutton** [comment]
The Office for Mac team intentionally made the 15.25 update available for only 24 hours in order to see if they got any scary analytics/feedback from customers. It's to be expected that you're not currently seeing the 15.25 update.

**Comment by timsutton** [comment]
I'll close this as I think this is expected for now. I believe you can also still retrieve the current 15.25 update using the InsiderSlow channel.
