### ISSUE TITLE
Oracle Java 8 Download Fails

### ISSUE THREAD

**Issue by jrr316** [autopkg/recipes#170]
AutoPkg Download of Oracle Java 8 runs fine, but while installing it via Munki there is a download error:

Oct 19 2016 10:52:01 -0400     Download error -1001: The request timed out.
Oct 19 2016 10:52:01 -0400     Headers: {u'Content-Length': u'63411817', u'Accept-Ranges': u'bytes', u'Keep-Alive': u'timeout=5, max=100', u'MS-Author-Via': u'DAV', u'Server': u'Apache', u'Last-Modified': u'Wed, 19 Oct 2016 13:37:35 GMT', u'Connection': u'Keep-Alive', u'Etag': u'"3c79669-53f37e964c5c0"', u'Date': u'Wed, 19 Oct 2016 14:50:55 GMT', u'Content-Type': u'application/octet-stream'}
Oct 19 2016 10:52:01 -0400 WARNING: Download of OracleJava8 failed: Error -1001: The request timed out.

Only happens with this version of Java, Any tips on getting this to work?

**Comment by gregneagle** [comment]
Sounds more like an issue with your webserver or your network.

**Comment by jrr316** [comment]
I would agree, but it is only this one recipe and download that is causing an issue.  All other installs are fine, even the 1.25GB Office installs.

**Comment by gregneagle** [comment]
and yet others, including myself, are having no issues with the recipe.

**Comment by jrr316** [comment]
Thank you for verifying.   Appreciate your help.

**Comment by gregneagle** [comment]
See https://groups.google.com/d/topic/munki-discuss/zq-3jHERBFo/discussion for one discovered cause of this issue. (Spoiler: not an Autopkg or Munki issue)
