### ISSUE TITLE
OracleJava8.munki update dmg fails, new pulls ok

### ISSUE THREAD

**Issue by 2wheeltinker** [autopkg/recipes#171]
Running the OracleJava8.munki, it kept reporting that the file had not changed. My current workaround is to go to /Library/AutoPkg/Cache/com.github.autopkg.munki.OracleJava8/downloads/ and delete the OracleJava8.dmg. That forces the recipe to re-download java and import it into munki correctly. 

So if OracleJava8.dmg exists, it won't download the latest version. If it doesn't exist, it has to since it can't re-use the existing cached download. (Which would be an older version) 

`
URLTextSearcher: No value supplied for CURL_PATH, setting default value of: /usr/bin/curl
URLTextSearcher: No value supplied for result_output_var_name, setting default value of: match
URLTextSearcher: Found matching text (url): http://download.oracle.com/otn-pub/java/jdk/8u111-b14/jre-8u111-macosx-x64.dmg
URLTextSearcher: Found matching text (match): http://download.oracle.com/otn-pub/java/jdk/8u111-b14/jre-8u111-macosx-x64.dmg
{'Output': {'match': 'http://download.oracle.com/otn-pub/java/jdk/8u111-b14/jre-8u111-macosx-x64.dmg',
            u'url': 'http://download.oracle.com/otn-pub/java/jdk/8u111-b14/jre-8u111-macosx-x64.dmg'}}
URLDownloader
{'Input': {'CURL_PATH': '/usr/bin/curl',
           'filename': u'OracleJava8.dmg',
           'request_headers': {
    Cookie = "oraclelicense=accept-securebackup-cookie";
},
           'url': 'http://download.oracle.com/otn-pub/java/jdk/8u111-b14/jre-8u111-macosx-x64.dmg'}}
URLDownloader: No value supplied for CHECK_FILESIZE_ONLY, setting default value of: False
URLDownloader: Item at URL is unchanged.
`

**Comment by timsutton** [comment]
I had something similar on my machine now that I've checked.

From looking at my cached DMG using `xattr -l`, it looks like the version I had cached (`1.8.101.13`) has a `Last-Modified` date of `Fri, 30 Sep 2016 21:23:31 GMT`, and if I remove that cached download, the newer `1.8.111.14` version has `Last-Modified` of `Fri, 23 Sep 2016 19:16:55 GMT`.

So for whatever reason, at some point AutoPkg ran and downloaded (a repost?) of an older version, but which has a newer Last-Modified date. Possibly their website was showing the older version as "latest" for a brief period.

There's not really a good solution for something like this happening besides just doing what you did. I'm not sure we've seen this with Oracle Java recipes before, hopefully it doesn't become a pattern.
