### ISSUE TITLE
MSOffice2016URLandUpdateInfoProvider contents differ from expected.

### ISSUE THREAD

**Issue by paulbloch** [autopkg/recipes#175]
sysadmin@beta: ~/autopkg 481$ autopkg run -v MSOutlook2016.munki
Processing MSOutlook2016.munki...
Failed.
Receipt written to /tmp/receipts/MSOutlook2016-receipt-20161202-100912.plist

The following recipes failed:
    MSOutlook2016.munki
        Processor MSOffice2016URLandUpdateInfoProvider contents differ from expected.
            Path: /Users/sysadmin/Library/AutoPkg/RecipeRepos/com.github.autopkg.recipes/MSOfficeUpdates/MSOffice2016URLandUpdateInfoProvider.py

Nothing downloaded, packaged or imported.

**Comment by gregneagle** [comment]
That's not an issue.

That's autopkg 1.0 telling you that something important in a recipe you use has changed and that you should pay attention, check it out, and update the trust info if you trust the changes.

https://github.com/autopkg/autopkg/wiki/AutoPkg-and-recipe-parent-trust-info

**Comment by paulbloch** [comment]
Thanks. I'm still getting used to the new trust info. 

It would be cool if these sort of errors mentioned trust failure as the cause of the error.

Paul

**Comment by gregneagle** [comment]
That's a good suggestion -- to make Trust Verification errors clearer when running a recipe

**Comment by gregneagle** [comment]
See if this helps: https://github.com/autopkg/autopkg/commit/0beb305bc3f2ecd87e2b64d81ac551d611340d7b

**Comment by paulbloch** [comment]
That code looks good. I’m not in a position to test it until next week.

Paul
