### ISSUE TITLE
Issue with Handbrake Munki Recipe

### ISSUE THREAD

**Issue by vmgstudio520** [autopkg/recipes#182]
Getting "The following failures occurred" for the following Munki recipe:
com.github.autopkg.munki.Handbrake

Message:
_"Error in com.github.autopkg.munki.Handbrake: Processor: URLDownloader: Error: Curl failure: The requested URL returned error: 404 Not Found (exit code 22)"_

**Comment by gregneagle** [comment]
See https://github.com/autopkg/recipes/issues/181

**Comment by brianwells** [comment]
The Sparkle feed has been updated and Handbrake.download recipe works once again. Yay!
