### ISSUE TITLE
Handbrake.download.recipe Curl failure

### ISSUE THREAD

**Issue by fkick** [autopkg/recipes#183]
Since the handbrake team has released 1.0, the handbrake.download.recipe no longer functions. I get the following error:

` Error in local.munki.Handbrake: Processor: URLDownloader: Error: Curl failure: The requested URL returned error: 404 Not Found (exit code 22)`

**Comment by gregneagle** [comment]
See https://github.com/autopkg/recipes/issues/181

**Comment by brianwells** [comment]
The Sparkle feed has been updated and Handbrake.download recipe works once again. And there was much rejoicing.
