### ISSUE TITLE
Adobe Developer ID changed again

### ISSUE THREAD

**Issue by orbsmiv** [autopkg/recipes#192]
Further to commit 71a9ca9 Adobe appear to have changed their Developer ID (at least for _Adobe Reader DC_) back to `Adobe Systems, Inc.`
Change again or wait to see if there's any further seesawing?!

**Comment by timsutton** [comment]
I didn't have an older copy of this app downloaded with which to compare, but it's funny that the package copied is dated early January:

```

**Comment by timsutton** [comment]
Now I see - I didn't realize that AdobeReaderDC.download is a child of AdobeReader.download, and they both verify the same expected cert names, but now since Adobe re-signed Adobe Reader with a different certname, we now have to split these verifications to separate recipes.
