### ISSUE TITLE
Spotify.download binary permissions

### ISSUE THREAD

**Issue by MichalMMac** [autopkg/recipes#196]
This is an upstream issue but I post here to warn you.

When you download Spotify.dmg vith `Spotify.download` recipe currently binaries in MacOS directory has permission bits set to 744. That's fine when owner is current user. Guess what happens when app is installed with Munki for example and files are owned by root. App does not launch.

**Comment by timsutton** [comment]
Others have seen this as well. My own inclination is to wait to see if Spotify resolves this in the next release. A one-liner like this could fix the permissions in a postinstall_script for example:

`chmod go+x /Applications/Spotify.app/Contents/Frameworks/Chromium\ Embedded\ Framework.framework/Chromium\ Embedded\ Framework /Applications/Spotify.app/Contents/Frameworks/Spotify\ Helper.app/Contents/MacOS/Spotify\ Helper /Applications/Spotify.app/Contents/MacOS/*`

**Comment by timsutton** [comment]
I just added a note to the `Spotify.munki` description to this effect in https://github.com/autopkg/recipes/commit/678607ec6ab64fc2b2a285af4415decf8bbfa3d0.

**Comment by hjuutilainen** [comment]
We've added this nopkg item to our Munki repo to fix already existing broken installations:
https://gist.github.com/hjuutilainen/dc6e8b77af0dced03271ef1a10471cb0
