### ISSUE TITLE
Sparkle error in Transmit recipes

### ISSUE THREAD

**Issue by krispayne** [autopkg/recipes#207]
Getting the following error when running my local override for Transmit for the last few days:
```
autopkg run -v Transmit.jss
Processing Transmit.jss...
SparkleUpdateInfoProvider
Error parsing XML from appcast feed.
Failed.
Receipt written to /Users/autopkg/Library/AutoPkg/Cache/local.jss.Transmit/receipts/Transmit-receipt-20170524-103016.plist

The following recipes failed:
    Transmit.jss
        Error in local.jss.Transmit: Processor: SparkleUpdateInfoProvider: Error: Error parsing XML from appcast feed.

Nothing downloaded, packaged or imported.
```

I tried updating the upstreams and creating a new override, but same result. Maybe this has to do with their recent acknowledgement of the WannaCrypt stuff? They might have possibly changed stuff up on their Sparkle feeds.

**Comment by timsutton** [comment]
This definitely would have been a result of https://panic.com/blog/stolen-source-code/. Thanks for reporting it!

**Comment by krispayne** [comment]
👍🏼
