### ISSUE TITLE
Evernote failing

### ISSUE THREAD

**Issue by RicknTx** [autopkg/recipes#214]
Whenever I try to run through the Evernote.munki.recipe it is failing saying that it cannot mount.  I was able to run through and do a manual mount of the dmg referenced.  I've cleaned out the directory and tried to start fresh, but it continually fails.  Any ideas what could be going wrong?  Started on 04JUL.

creating pkginfo for /Users/Shared/Jenkins/Library/AutoPkg/Cache/com.github.autopkg.munki.Evernote/Evernote.dmg failed: Could not mount /Users/Shared/Jenkins/Library/AutoPkg/Cache/com.github.autopkg.munki.Evernote/Evernote.dmg!

Failed.
Processing Evernote.munki.recipe...

**Comment by gregneagle** [comment]
Did you check to see if what is being downloaded currently is actually a valid dmg file?

**Comment by RicknTx** [comment]
Hi Greg, yes..  I was able to go in afterward and actually mount the freshly downloaded dmg file ok and see the files.  That's what had me puzzled.  I've cleared it out and then let it pull it down fresh a few times, each getting this same could not mount error.  I've also updated the recipes to make sure I didn't have anything stale out there, even though this one hasn't been updated in several months from what I can tell here online.

**Comment by gregneagle** [comment]
Works here:

```
% autopkg run Evernote.munki
Processing Evernote.munki...

The following new items were imported into Munki:
    Name      Version  Catalogs  Pkginfo Path                         Pkg Repo Path                      
    ----      -------  --------  ------------                         -------------                      
    Evernote  6.11.1   testing   apps/Evernote/Evernote-6.11.1.plist  apps/Evernote/Evernote-6.11.1.dmg  

The following new items were downloaded:
    Download Path                                                                                                        
    -------------                                                                                                        
    /Users/gneagle/Library/AutoPkg/Cache/com.github.autopkg.munki.Evernote/downloads/Evernote_RELEASE_6.11.1_455059.zip
```

**Comment by gregneagle** [comment]
If you closed it does that mean there's not really an issue?

**Comment by RicknTx** [comment]
Hi Greg, sorry.. my comment didn't post there..   I cleared things out again for the cache and re-ran it.  Things seem to be working fine again.  Sorry for the mixup..  Thank you for the quick replies as well!!
