### ISSUE TITLE
munkitools3.munki.recipe Unexpected GitHub API Status Code

### ISSUE THREAD

**Issue by fkick** [autopkg/recipes#236]
When running the munkitools3.munki.recipe I'm getting the following error:

```
Error opening URL: https://api.github.com/repos/munki/munki/releases
[SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:590)

Unexpected GitHub API status code None.
```

**Comment by gregneagle** [comment]
See https://github.com/autopkg/autopkg/issues/408

This will be resolved by Autopkg 1.0.4; or you can run Autopkg under macOS 10.13+
