### ISSUE TITLE
TextWrangler Recipe no longer works.

### ISSUE THREAD

**Issue by dcdsbmm** [autopkg/recipes#240]
The Textwrangler App has been sunset by the dev. 
https://www.barebones.com/products/textwrangler/

The recipe now gives an error trying to download the application. (Looks like the dev is pushing links to their new bbedit software).

`autopkg run -v TextWrangler.munki
Processing TextWrangler.munki...
BarebonesURLProvider
BarebonesURLProvider: Found URL https://s3.amazonaws.com/BBSW-download/BBEdit_12.0.dmg
URLDownloader
Curl failure: The requested URL returned error: 403 Forbidden (exit code 22)
Failed.
`

**Comment by timsutton** [comment]
Since TW will never be updated, I don’t think it makes sense to keep this recipe around.

**Comment by gregneagle** [comment]
...and they are gone!
https://github.com/autopkg/recipes/commit/0193f2063804a4e0069a768a07de70ec0baf3070
