### ISSUE TITLE
AdobeFlashURLProvider.py does not pass headers when it requests a URL.

### ISSUE THREAD

**Issue by primalcurve** [autopkg/recipes#241]
Hi All, 

I've already made a fix for this, but I cannot publish branches to this repo so I guess I'll start here. This processor does not utilize the request_headers key like other processors does. In my environment, this means that it fails. I would like to update it at the source rather than forking it, so here I am. I have attached my new version of the processor based on the original and URLTextSearcher.py. It seems to work well for me but I'm sure you'll find something I missed.

Thanks,
-primalcurve
[AdobeFlashURLProvider.py.zip](https://github.com/autopkg/recipes/files/1849331/AdobeFlashURLProvider.py.zip)

**Comment by gregneagle** [comment]
This sounds interesting. Can you please make a Pull Request?

Hint: you fork this repo, make your changes to your fork, then create a pull request from your fork.

**Comment by gregneagle** [comment]
Closing this issue on the assumption it will be replaced with a PR.
