### ISSUE TITLE
Oracle Java 9 recipe needs updating to Java 10

### ISSUE THREAD

**Issue by dcdsbmm** [autopkg/recipes#245]
Java SE 9 has reached end of support. Users of Java SE 9 should switch to Java SE 10.
http://www.oracle.com/technetwork/java/javase/downloads/jre9-downloads-3848532.html

The new download page is:

http://www.oracle.com/technetwork/java/javase/downloads/jre10-downloads-4417026.html

**Comment by gregneagle** [comment]
There are new OracleJava10 recipes.
