### ISSUE TITLE
Why does MozillaURLProvider.py import all these apparently unused libraries?

### ISSUE THREAD

**Issue by jsilverman-blispay** [autopkg/recipes#248]
This is really just a question of clarification. Perhaps there's a forum that is better for this? If so, please point me that way.

The MozillaURLProvider.py program has 4 or 5 libs imported at the top that appear to go entirely unused.

Is this just a symptom of copy/paste from previous, similar, provider recipes? Or are they used under the hood in a non-obvious way?

Lines 18 - 24

    import re
    import urllib
    import urllib2
    import urlparse
    from distutils.version import LooseVersion

    from autopkglib import Processor, ProcessorError

Regex appears unused
URL Libs all appear unused
And idk what LooseVersion is

Comparing this Python program to the PuppetURLProvider.py, for example, that one actually does use the URL and Regex libraries to download some resource and parse the HTML.

Thank you for clarifying this

**Comment by gregneagle** [comment]
Most likely these are left over from older versions of the processor, an examination of the git history might be instructive.

You could create a PR to clean those up and make other PEP-8 fixes if you'd like.

Since this isn't actually a code issue I'm going to close this.
