### ISSUE TITLE
Issue with adobeflashplayer.munki

### ISSUE THREAD

**Issue by skeletalcell** [autopkg/recipes#251]
I'm new to munki, autopkg, and autopkgr.  I've set it all up this week and have it all working.  Tested everything out and Google, Firefox, Java, VLC, Adobe AIR all work fine.  I cannot get adobe flash to work.
I keep receiving:

>        Error in local.munki.AdobeFlashPlayer: Processor: AdobeFlashURLProvider: Error: Could not retrieve URL http://fpdownload2.macromedia.com/get/flashplayer/update/current/xml/version_en_mac_pl.xml:   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                         Dload  Upload   Total   Spent    Left  Speed
        
          0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
          0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
          0     0    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0
          0     0    0     0    0     0      0      0 --:--:--  0:00:03 --:--:--     0
          0     0    0     0    0     0      0      0 --:--:--  0:00:04 --:--:--     0
          0     0    0     0    0     0      0      0 --:--:--  0:00:05 --:--:--     0
          0     0    0     0    0     0      0      0 --:--:--  0:00:06 --:--:--     0
          0     0    0     0    0     0      0      0 --:--:--  0:00:07 --:--:--     0
          0     0    0     0    0     0      0      0 --:--:--  0:00:08 --:--:--     0
          0     0    0     0    0     0      0      0 --:--:--  0:00:09 --:--:--     0
          0     0    0     0    0     0      0      0 --:--:--  0:00:10 --:--:--     0
          0     0    0     0    0     0      0      0 --:--:--  0:00:11 --:--:--     0
          0     0    0     0    0     0      0      0 --:--:--  0:00:12 --:--:--     0
          0     0    0     0    0     0      0      0 --:--:--  0:00:13 --:--:--     0
          0     0    0     0    0     0      0      0 --:--:--  0:00:14 --:--:--     0
          0     0    0     0    0     0      0      0 --:--:--  0:00:15 --:--:--     0
          0     0    0     0    0     0      0      0 --:--:--  0:00:16 --:--:--     0
          0     0    0     0    0     0      0      0 --:--:--  0:00:17 --:--:--     0
          0     0    0     0    0     0      0      0 --:--:--  0:00:18 --:--:--     0
        curl: (56) Recv failure: Operation timed out

I tried googling as much as I could and could not find a resolution to the issue.
I'm also having issues with AdobeReaderDC

>Error in local.munki.AdobeReaderDC: Processor: URLDownloader: Error: Curl failure: Recv failure: Operation timed out (exit code 56)

I haven't looked up the Reader issue as much.  More concerned about the Flash issue.  Any help is much appreciated!

**Comment by gregneagle** [comment]
This is not a general support forum; you will have better luck posting to the autopkg-discuss Google Group.

**Comment by skeletalcell** [comment]
Thanks
