### ISSUE TITLE
OracleJava9 fails to install

### ISSUE THREAD

**Issue by hugo4711** [autopkg/recipes#259]
The Download URL seems to be changed because running `autopkg run -vv OracleJava9.munki` gives:

`Error in com.github.autopkg.munki.OracleJava9: Processor: URLTextSearcher: Error: No match found on URL: http://www.oracle.com/technetwork/java/javase/downloads/jre9-downloads-3848532.html
`

**Comment by 8bitp** [comment]
Java 9 has reached EOL.
source: http://www.oracle.com/technetwork/java/eol-135779.html

I don't think there exist another openly accessible download link without having to log-in.

**Comment by n8felton** [comment]
This can likely be closed with https://github.com/autopkg/recipes/issues/290 and https://github.com/autopkg/recipes/pull/427.
