### ISSUE TITLE
TextMate2 URL 

### ISSUE THREAD

**Issue by mattydee99** [autopkg/recipes#284]
To get the latest release, the url needs to  be:
https://api.textmate.org/downloads/release?os=10.9
pulls in rc.10 (at the time of this note)

https://api.textmate.org/downloads/release
pulls in rc.4

**Comment by micmil** [comment]
https://api.textmate.org/downloads/release?os=10.12 pulls 2.0 (non rc) release.

**Comment by homebysix** [comment]
This will be addressed by #311.
