### ISSUE TITLE
OracleJava8 download URL has changed

### ISSUE THREAD

**Issue by krispayne** [autopkg/recipes#290]
The new URL on the page is (currently):
`https://download.oracle.com/otn/java/jdk/8u211-b12/478a62b7d4e34b78b671c754eaaf38ab/jre-8u211-macosx-x64.dmg`
Should the regex pattern in OracleJava8.download.recipe change to:
`<string>(?P&lt;url&gt;https://download.oracle.com/otn/java/jdk/.*?/jre-8.*?x64.dmg)</string>`

**Comment by gregneagle** [comment]
More likely this recipe should be deprecated.

Oracle has changed the licensing for Java 8 and it is no longer free for most usage scenarios.

If people want to ignore the licensing changes that's on them, but I don't think "official" autopkg recipes should encourage that.

**Comment by krispayne** [comment]
That's also fair.

I'm not actively deploying this anyway, just stumbled on it since my JSS had an update (forgot I had that notification!)
