### ISSUE TITLE
Adobe Reader DC, Downloads incorrect version

### ISSUE THREAD

**Issue by nickthemacguy** [autopkg/recipes#301]
The Adobe Reader DC recipe downloads version 19.010.20099 instead of 19.012.20034 (One version behind) 

Should MAJOR_VERSION_DEFAULT = "11"  be changed to MAJOR_VERSION_DEFAULT = "14" ?

**Comment by gregneagle** [comment]
There is no such key in the AdobeReaderDC.download.recipe.

Maybe the OS_VERSION needs to be bumped?

**Comment by nickthemacguy** [comment]
Hi Greg, sorry I meant MAJOR_VERSION_DEFAULT = "11" and OS_VERSION_DEFAULT = '10.8.0' inside of AdobeReaderURLProvider.py and potentially       <key>OS_VERSION</key>
        <string>10.12.0</string> inside of the recipe

**Comment by eenblam** [comment]
During the recent Adobe security release, we were able to work around this by just adding an override for `OS_VERSION 10.12.0`. I think that's all that needs to be updated in the recipe.

There are several PR's open that do exactly this: https://github.com/autopkg/recipes/pull/299

@gregneagle IIRC this is needed to get that important security update Adobe pushed out recently.

**Comment by eenblam** [comment]
Sorry; just looked and saw that this fix is already in master.

**Comment by nmcspadden** [comment]
So can this issue be closed?

**Comment by nickthemacguy** [comment]
This has issue has been resolved

**Comment by rrenstrom** [comment]
OS_VERSION also needs to be bumped in AdobeReaderDC.munki.recipe
