### ISSUE TITLE
AdobeReaderURLProvider.py: No module named URLGetter

### ISSUE THREAD

**Issue by adam-koho** [autopkg/recipes#328]
**Describe the problem**
A clear and concise description of what the problem is.
I cannot run the recipe to create policy and upload package to JAMF Pro. The error is `AdobeReaderURLProvider.py: No module named URLGetter`. Other recipes having the same configuration work.

**Preferences contents**
*BE SURE TO SANITIZE ANY SENSITIVE DATA SUCH AS PASSWORDS OR ADDRESSES.*
Provide or link to a [gist](https://gist.github.com) of the output of `defaults read com.github.autopkg`, or the contents of your external `--prefs` file. 
[https://gist.github.com/adam-koho/1ebfa32955d9ff3bbd8e8c8ea036645b](https://gist.github.com/adam-koho/1ebfa32955d9ff3bbd8e8c8ea036645b)

**AutoPkg output**
*BE SURE TO SANITIZE ANY SENSITIVE DATA SUCH AS PASSWORDS OR ADDRESSES.*
Provide or link to a [gist](https://gist.github.com) of the output of `autopkg run -vvvv <RecipeName>`, or any other command you are running. Please include as much data as possible.
[https://gist.github.com/adam-koho/1ebfa32955d9ff3bbd8e8c8ea036645b](https://gist.github.com/adam-koho/1ebfa32955d9ff3bbd8e8c8ea036645b)

**Expected behavior**
A clear and concise description of what you expected to happen. What specific part of the recipe or AutoPkg run did not behave correctly?
I expected to upload the policy and the package to JAMF Pro.
 
**Version (please complete the following information):**
- OS version: **MacOS 10.15.1**
- AutoPkg Version: **1.5.1**

**Comment by homebysix** [comment]
Hi @adam-koho - The latest version of AutoPkg is 1.4. Perhaps you have _AutoPkgr_ 1.5.1?

Please run `autopkg version`, and if it's not 1.4 you may want to update.

**Comment by nmcspadden** [comment]
I'm unable to reproduce this on AutoPkg 1.4 or 2.0b3.

**Comment by adam-koho** [comment]
Hey @homebysix , it's my bad.
AutoPkg Version: 1.3.1
AutoPkgr Version: 1.5.1
I updated to AutoPkg Version: 1.4. The error's still there though

**Comment by homebysix** [comment]
Does the error persist after you do the following?

```
autopkg repo-update recipes
autopkg update-trust-info AdobeReaderDC-selfservice.jss
autopkg run -v "AdobeReaderDC-selfservice.jss.recipe"
```

**Comment by adam-koho** [comment]
Hey @homebysix , it was a magic! It works now. I only updated the repo by using AutoPKGR. Thank you!

**Comment by adam-koho** [comment]
There is another error with Wireshark. I did updated repos and trust info
```
autopkg run -v "Wireshark-selfservice.jss.recipe"

Processing Wireshark-selfservice.jss.recipe...
URLTextSearcher
URLTextSearcher: Found matching text (match): Wireshark 3.0.6 Intel 64.dmg
URLDownloader
URLDownloader: Item at URL is unchanged.
URLDownloader: Using existing /Users/adam/Library/AutoPkg/Cache/local.jss.Wireshark-selfservice/downloads/Wireshark 3.0.6 Intel 64.dmg
EndOfCheckPhase
CodeSignatureVerifier
CodeSignatureVerifier: Mounted disk image /Users/adam/Library/AutoPkg/Cache/local.jss.Wireshark-selfservice/downloads/Wireshark 3.0.6 Intel 64.dmg
Error processing path '/private/tmp/dmg.aNT58R/Wireshark*.pkg' with glob. 
Failed.
Receipt written to /Users/adam/Library/AutoPkg/Cache/local.jss.Wireshark-selfservice/receipts/Wireshark-selfservice.jss-receipt-20191127-134535.plist

The following recipes failed:
    Wireshark-selfservice.jss.recipe
        Error in local.jss.Wireshark-selfservice: Processor: CodeSignatureVerifier: Error: Error processing path '/private/tmp/dmg.aNT58R/Wireshark*.pkg' with glob. 

Nothing downloaded, packaged or imported.
```

**Comment by homebysix** [comment]
The Wireshark error is fundamentally different than the Adobe Reader error you first posted about, so it deserves its own issue.

The next question is which repository the issue should be opened on, because the Wireshark recipes are not in this repository. Judging on the identifier of the Wireshark recipe you're running, I'm guessing you're using this recipe chain:

- com.github.jss-recipes.jss.Wireshark
- com.github.autopkg.cgerke-recipes.pkg.Wireshark
- com.github.autopkg.cgerke-recipes.download.Wireshark

Since the download recipe is the one which contains CodeSignatureVerifier, the cgerke-recipes repository is the relevant one. [Check that repo's issues](https://github.com/autopkg/cgerke-recipes/issues?utf8=✓&q=is%3Aissue+wireshark) for related questions, and if you don't see anything related, then open a new issue there. Thanks!
