### ISSUE TITLE
remove GoogleChrome from https://github.com/autopkg/recipes

### ISSUE THREAD

**Issue by anujgoyal** [autopkg/recipes#340]
Please remove GoogleChrome from https://github.com/autopkg/recipes

Customers are running into issues with the AutoPkg version.
https://bugs.chromium.org/p/chromium/issues/detail?id=1065730

There is an official Chrome PKG file now available at:
https://cloud.google.com/chrome-enterprise/browser/download/

The two PKG files are not compatible.

If you are an Enterprise customer (with a Google support contract) please use the PKG file at https://cloud.google.com/chrome-enterprise/browser/download/

**Comment by gregneagle** [comment]
If you don't like the results of using the GoogleChrome recipes, don't use them.

We have no idea what "Customers are running into issues with the AutoPkg version." means -- the recipes merely download the official consumer release and import them into various software distribution mechanisms.

It's interesting that there is now a package for "Chrome Enterprise" but I'd say that's up to each organization to decide if they want to use that.

**Comment by gregneagle** [comment]
https://bugs.chromium.org/p/chromium/issues/detail?id=1065730#c7

You are seeing the effects of bundle relocation. The official Google Chrome package is authored in such a way that the macOS installer will update a copy of Google Chrome that is found on disk but not necessarily at /Applications/Google Chrome.app.

This is not autopkg-specific. You'd see the same behavior if there was a copy of Google Chrome.app sitting on the user's Desktop, or in /Users/Shared, or literally anywhere on disk other than /Applications.

The GoogleChrome.pkg.recipe in this repo will be changed to have a package identifier that is _not_ com.google.Chrome, as that indeed should be reserved for the official package from Google, but that will not address the issue with Google's official package. That (if Google wants to address it) will require changes on Google's end.
