### ISSUE TITLE
Add/fork - Helicon Soft

### ISSUE THREAD

**Issue by TekTekkers** [autopkg/recipes#395]
Hi, 

Could you please review & fork these to make those recipes available to the AutoPkg community, if all is good

https://github.com/TekTekkers/TekTekkers-recipes/tree/main/Helicon%20Soft

**Comment by homebysix** [comment]
Hello @TekTekkers. No need for another fork in this case. You can push these recipes to your repository in the autopkg org, which is here: https://github.com/autopkg/TekTekkers-recipes
