### ISSUE TITLE
Dropbox.pkg fails to provide %version% and is parsing CFBundleVersion for no reason

### ISSUE THREAD

**Issue by grahampugh** [autopkg/recipes#398]
**Describe the problem**
`Dropbox.pkg` fails to provide `%version%`. This makes extra work or failure when making child recipes such as .jss or .jamf recipes. Additionally, it is using `CFBundleVersion` as the version string instead of `CFBundleShortVersionString`. I don't know why.

**Preferences contents**
Irrelevant

**AutoPkg output**
Using [Dropbox.jamf](https://github.com/eth-its/autopkg-mac-recipes-yaml/blob/5283bd285a1a9158f12c3eeb70c8556bb9a257c8/Jamf_Recipes/Dropbox.jamf.recipe.yaml):

```
% autopkg run -v Dropbox.jamf
Processing Dropbox.jamf...
Receipt written to /tmp/receipts/Dropbox-receipt-20210827-160813.plist

The following recipes failed:
    Dropbox.jamf
        com.github.grahampugh.recipes.commonprocessors/VersionRegexGenerator requires missing argument version

Nothing downloaded, packaged or imported.
Recipe failed
```

**Expected behavior**
`%version%` should be outputted for use by child processes. `CFBundleShortVersionString` should be used as the version.

I see no reason why this recipe cannot just use a standard `AppPkgCreator` processor. I have created my own [Dropbox.pkg recipe here](https://github.com/eth-its/autopkg-mac-recipes-yaml/blob/main/PKG_Recipes/Dropbox.pkg.recipe.yaml) and it works perfectly well. I can PR it if requested, though I only work with YAML recipes nowadays.

**Version (please complete the following information):**
- OS version: 11.4
- AutoPkg Version: 2.3.1

**Comment by homebysix** [comment]
Resolved by #399
