### ISSUE TITLE
AdobeReaderDC.pkg.recipe error

### ISSUE THREAD

**Issue by killer23d** [autopkg/recipes#425]
For the past few weeks, I am getting issues with running AdobeReaderDC recipe:

`<key>RecipeError</key>
			<string>Error in local.download.AdobeReaderDC: Processor: AdobeReaderURLProvider: Error: Command '['/usr/bin/curl', '--compressed', '--location', '--header', 'x-requested-with: XMLHttpRequest', 'http://get.adobe.com/reader/webservices/json/standalone/?platform_type=Macintosh&amp;platform_dist=OSX&amp;platform_arch=x86-32&amp;platform_misc=10.15.0&amp;language=English&amp;eventname=readerotherversions']' returned non-zero exit status 92.</string>
		</dict>
	</array>`

**Comment by timnottom** [comment]
Hey, check out: https://github.com/autopkg/recipes/issues/424 It's up to Adobe to fix this.

**Comment by nmcspadden** [comment]
Closing as duplicate
