### ISSUE TITLE
Wrong pattern in line 189 munkitools.munki.recipe

### ISSUE THREAD

**Issue by rzlinder** [autopkg/recipes#441]
When I use the recipe "munkitools.munki.recipe" AutoPkg is replacing munkitools_app.pkg with munkitools_app_usage.pkg.
When I change line 189 in "munkitools.munki.recipe" to the same as in "munkitools5.munki.recipe" then it works.

`<string>%RECIPE_CACHE_DIR%/unpack/munkitools_app*.pkg</string>`
`<string>%RECIPE_CACHE_DIR%/unpack/munkitools_app[.-]*pkg</string>`

**Comment by mariuslangz** [comment]
Getting the same error here when using munkitools.munki.recipe - Although I cannot get the correct munkitools_app when I change line 189 in the parent recipe in my end
