### ISSUE TITLE
XQuartz sparkle URL has changed

### ISSUE THREAD

**Issue by 1-rphillips** [autopkg/recipes#448]
**Describe the problem**
This affects XQuartz.download.recipe, and any recipes that depend on XQuartz.download.recipe.

It looks like the Xquartz maintainer(s) have moved the Sparkle feeds (appcast_url) from

https://www.xquartz.org/releases/sparkle/____.xml

to

https://www.xquartz.org/releases/sparkle-r1/____.xml

The appcast_url needs to be updated to sparkle-r1 in order to be able to pull the latest release(s). Also see:
https://www.xquartz.org/releases/index.html [and note the URLs used in the defaults commands listed]

The old Sparkle feed URLs still function at the moment, but they do not provide the latest release(s). 
...And one more thing - there's also an "alpha" branch now (so...{alpha, beta, release} are all options), but I care less about that.

**Comment by 1-rphillips** [comment]
PR submitted for this: https://github.com/autopkg/recipes/pull/449

**Comment by 1-rphillips** [comment]
also PR: https://github.com/autopkg/recipes/pull/450

**Comment by gregneagle** [comment]
PRs merged
