### ISSUE TITLE
Feature request - munkitools6 recipe should support the MacAdmins signed releases

### ISSUE THREAD

**Issue by robertryansqub** [autopkg/recipes#457]
With the 6.3 release of Munki there is a good argument for using the MacAdmins signed & notified Munki packages versus the upstream. The current munkitools6 recipe, by design, does not provide for overrides of the source GitHub site. While it is trivial to make a copy of the recipe and edit manually it would be preferable to have a native override.

**Comment by gregneagle** [comment]
This was addressed with a separate recipe: https://github.com/autopkg/recipes/blob/master/munkitools/munkitools6-signed.munki.recipe
