### ISSUE TITLE
AdobeReader recipes fail to find new versions

### ISSUE THREAD

**Issue by bjohnson-MHC** [autopkg/recipes#480]
**Describe the problem**
AdobeReader recipes began to fail after version 23.008.20423. The recipe will not pull down  23.008.20458 or 23.008.20470. I initially noticed it with the .pkg recipe and verified that the problem also occurred with an unmodified override of the .download recipe, so it looks like Adobe moved our cheese.

**Preferences contents**
*BE SURE TO SANITIZE ANY SENSITIVE DATA SUCH AS PASSWORDS OR ADDRESSES.*
{
    "API_PASSWORD" = **********;
    "API_USERNAME" = "*********";
    "CACHE_DIR" = "/Users/USER/Library/AutoPkg/Cache";
    "FAIL_RECIPES_WITHOUT_TRUST_INFO" = 1;
    "GIT_PATH" = "/Library/Developer/CommandLineTools/usr/bin/git";
    "JSS_REPOS" =     (
    );
    "JSS_URL" = "https://***************";
    "JSS_VERIFY_SSL" = 1;
    "RECIPE_OVERRIDE_DIRS" = "/Users/USER/Library/AutoPkg/RecipeOverrides";
    "RECIPE_REPOS" =     {
        "/Users/USER/Library/AutoPkg/RecipeRepos/com.github.autopkg.dataJAR-recipes" =         {
            URL = "https://github.com/autopkg/dataJAR-recipes.git";
        };
        "/Users/USER/Library/AutoPkg/RecipeRepos/com.github.autopkg.grahampugh-recipes" =         {
            URL = "https://github.com/autopkg/grahampugh-recipes.git";
        };
        "/Users/USER/Library/AutoPkg/RecipeRepos/com.github.autopkg.haircut-recipes" =         {
            URL = "https://github.com/autopkg/haircut-recipes.git";
        };
        "/Users/USER/Library/AutoPkg/RecipeRepos/com.github.autopkg.hansen-m-recipes" =         {
            URL = "https://github.com/autopkg/hansen-m-recipes.git";
        };
        "/Users/USER/Library/AutoPkg/RecipeRepos/com.github.autopkg.hjuutilainen-recipes" =         {
            URL = "https://github.com/autopkg/hjuutilainen-recipes.git";
        };
        "/Users/USER/Library/AutoPkg/RecipeRepos/com.github.autopkg.homebysix-recipes" =         {
            URL = "https://github.com/autopkg/homebysix-recipes.git";
        };
        "/Users/USER/Library/AutoPkg/RecipeRepos/com.github.autopkg.jazzace-recipes" =         {
            URL = "https://github.com/autopkg/jazzace-recipes.git";
        };
        "/Users/USER/Library/AutoPkg/RecipeRepos/com.github.autopkg.jessepeterson-recipes" =         {
            URL = "https://github.com/autopkg/jessepeterson-recipes.git";
        };
        "/Users/USER/Library/AutoPkg/RecipeRepos/com.github.autopkg.jss-recipes" =         {
            URL = "https://github.com/autopkg/jss-recipes.git";
        };
        "/Users/USER/Library/AutoPkg/RecipeRepos/com.github.autopkg.killahquam-recipes" =         {
            URL = "https://github.com/autopkg/killahquam-recipes.git";
        };
        "/Users/USER/Library/AutoPkg/RecipeRepos/com.github.autopkg.novaksam-recipes" =         {
            URL = "https://github.com/autopkg/novaksam-recipes.git";
        };
        "/Users/USER/Library/AutoPkg/RecipeRepos/com.github.autopkg.nstrauss-recipes" =         {
            URL = "https://github.com/autopkg/nstrauss-recipes.git";
        };
        "/Users/USER/Library/AutoPkg/RecipeRepos/com.github.autopkg.recipes" =         {
            URL = "https://github.com/autopkg/recipes.git";
        };
        "/Users/USER/Library/AutoPkg/RecipeRepos/com.github.autopkg.rtrouton-recipes" =         {
            URL = "https://github.com/autopkg/rtrouton-recipes.git";
        };
        "/Users/USER/Library/AutoPkg/RecipeRepos/com.github.autopkg.rustymyers-recipes" =         {
            URL = "https://github.com/autopkg/rustymyers-recipes.git";
        };
        "/Users/USER/Library/AutoPkg/RecipeRepos/com.github.autopkg.scriptingosx-recipes" =         {
            URL = "https://github.com/autopkg/scriptingosx-recipes.git";
        };
        "/Users/USER/Library/AutoPkg/RecipeRepos/com.github.autopkg.timsutton-recipes" =         {
            URL = "https://github.com/autopkg/timsutton-recipes.git";
        };
        "/Users/USER/Library/AutoPkg/RecipeRepos/com.github.hjuutilainen.autopkg-virustotalanalyzer" =         {
            URL = "https://github.com/hjuutilainen/autopkg-virustotalanalyzer.git";
        };
    };
    "RECIPE_REPO_DIR" = "/Users/USER/Library/AutoPkg/RecipeRepos";
    "RECIPE_SEARCH_DIRS" =     (
        ".",
        "~/Library/AutoPkg/Recipes",
        "/Library/AutoPkg/Recipes",
        "/Users/USER/Library/AutoPkg/RecipeRepos/com.github.autopkg.recipes",
        "/Users/USER/Library/AutoPkg/RecipeRepos/com.github.autopkg.homebysix-recipes",
        "/Users/USER/Library/AutoPkg/RecipeRepos/com.github.autopkg.rtrouton-recipes",
        "/Users/USER/Library/AutoPkg/RecipeRepos/com.github.autopkg.grahampugh-recipes",
        "/Users/USER/Library/AutoPkg/RecipeRepos/com.github.hjuutilainen.autopkg-virustotalanalyzer",
        "/Users/USER/Library/AutoPkg/RecipeRepos/com.github.autopkg.dataJAR-recipes",
        "/Users/USER/Library/AutoPkg/RecipeRepos/com.github.autopkg.haircut-recipes",
        "/Users/USER/Library/AutoPkg/RecipeRepos/com.github.autopkg.hansen-m-recipes",
        "/Users/USER/Library/AutoPkg/RecipeRepos/com.github.autopkg.jazzace-recipes",
        "/Users/USER/Library/AutoPkg/RecipeRepos/com.github.autopkg.jessepeterson-recipes",
        "/Users/USER/Library/AutoPkg/RecipeRepos/com.github.autopkg.jss-recipes",
        "/Users/USER/Library/AutoPkg/RecipeRepos/com.github.autopkg.novaksam-recipes",
        "/Users/USER/Library/AutoPkg/RecipeRepos/com.github.autopkg.nstrauss-recipes",
        "/Users/USER/Library/AutoPkg/RecipeRepos/com.github.autopkg.scriptingosx-recipes",
        "/Users/USER/Library/AutoPkg/RecipeRepos/com.github.autopkg.timsutton-recipes",
        "/Users/USER/Library/AutoPkg/RecipeRepos/com.github.autopkg.hjuutilainen-recipes",
        "/Users/USER/Library/AutoPkg/RecipeRepos/com.github.autopkg.rustymyers-recipes",
        "/Users/USER/Library/AutoPkg/RecipeRepos/com.github.autopkg.killahquam-recipes"
    );

**AutoPkg output**
autopkg run -v local.download.AdobeReader
Processing local.download.AdobeReader...
AdobeReaderURLProvider
AdobeReaderURLProvider: [displayName] : Reader 2023.008.20423 for Mac
AdobeReaderURLProvider: [version]     : 23.008.20423
AdobeReaderURLProvider: [download_url]: https://ardownload2.adobe.com/pub/adobe/reader/mac/AcrobatDC/2300820423/AcroRdrDC_2300820423_MUI.dmg
URLDownloader
URLDownloader: Item at URL is unchanged.
URLDownloader: Using existing /Users/USER/Library/AutoPkg/Cache/local.download.AdobeReader/downloads/AdobeReader.dmg
EndOfCheckPhase
CodeSignatureVerifier
CodeSignatureVerifier: Mounted disk image /********/AutoPkg/Cache/local.download.AdobeReader/downloads/AdobeReader.dmg
CodeSignatureVerifier: Using path '/private/tmp/dmg.6zyb5K/AcroRdrDC_2300820423_MUI.pkg' matched from globbed '/private/tmp/dmg.6zyb5K/*.pkg'.
CodeSignatureVerifier: Verifying installer package signature...
CodeSignatureVerifier: Package "AcroRdrDC_2300820423_MUI.pkg":
CodeSignatureVerifier:    Status: signed by a developer certificate issued by Apple for distribution
CodeSignatureVerifier:    Notarization: trusted by the Apple notary service
CodeSignatureVerifier:    Signed with a trusted timestamp on: 2023-12-09 08:54:13 +0000
CodeSignatureVerifier:    Certificate Chain:
CodeSignatureVerifier:     1. Developer ID Installer: Adobe Inc. (JQ525L2MZD)
CodeSignatureVerifier:        Expires: 2027-02-01 22:12:15 +0000
CodeSignatureVerifier:        SHA256 Fingerprint:
CodeSignatureVerifier:            97 9A 81 BE 07 15 BA 87 99 0E AD DC AE 97 A7 98 08 19 8A 1E DE 0F 
CodeSignatureVerifier:            4A 42 0D CE 38 96 80 A1 CE BF
CodeSignatureVerifier:        ------------------------------------------------------------------------
CodeSignatureVerifier:     2. Developer ID Certification Authority
CodeSignatureVerifier:        Expires: 2027-02-01 22:12:15 +0000
CodeSignatureVerifier:        SHA256 Fingerprint:
CodeSignatureVerifier:            7A FC 9D 01 A6 2F 03 A2 DE 96 37 93 6D 4A FE 68 09 0D 2D E1 8D 03 
CodeSignatureVerifier:            F2 9C 88 CF B0 B1 BA 63 58 7F
CodeSignatureVerifier:        ------------------------------------------------------------------------
CodeSignatureVerifier:     3. Apple Root CA
CodeSignatureVerifier:        Expires: 2035-02-09 21:40:36 +0000
CodeSignatureVerifier:        SHA256 Fingerprint:
CodeSignatureVerifier:            B0 B1 73 0E CB C7 FF 45 05 14 2C 49 F1 29 5E 6E DA 6B CA ED 7E 2C 
CodeSignatureVerifier:            68 C5 BE 91 B5 A1 10 01 F0 24
CodeSignatureVerifier: 
CodeSignatureVerifier: Signature is valid
CodeSignatureVerifier: Authority name chain is valid
Receipt written to /Users/USER/Library/AutoPkg/Cache/local.download.AdobeReader/receipts/local.download-receipt-20240116-082004.plist

Nothing downloaded, packaged or imported.

**Expected behavior**
I expected AutoPkg to find the newer version of AdobeReader dmg and download it.

**Version (please complete the following information):**
- OS version: 13.6.3
- AutoPkg Version: 2.7.2

**Comment by bjohnson-MHC** [comment]
Annnd . . . today it works. Nothing changed on my end, the recipe successfully downloaded and packaged from the latest (current version) DMG.

**Comment by gregneagle** [comment]
would imply the _vendor_ changed/updated something upstream.
