### ISSUE TITLE
MSOfficeMacProduct.download misleading description

### ISSUE THREAD

**Issue by grahampugh** [autopkg/recipes#481]
**Describe the problem**
The description of this recipe states:
```
Downloads a Microsoft Office Mac product. This recipe should only
ever be used as a child recipe with specific values overridden.
```

I think this means **parent**, not **child**. This recipe should always be a parent recipe (and it is, to all the specific MS Office recipes in this repo).

**Comment by gregneagle** [comment]
Addressed here: https://github.com/autopkg/recipes/commit/db02edcc4fad1325e3f44ea31aa387a4ad39c998
