### ISSUE TITLE
SassafrasK2Client: mpkg no longer being released

### ISSUE THREAD

**Issue by jazzace** [autopkg/recipes#57]
As per a recent discussion on Twitter and a follow-up with the developer, we've confirmed that the mpkg version of the K2 Client installer is no longer being released with new releases from Sassafras. However, their newer flat package installers can be configured with k2clientconfig command line tool, which is now made available separately (it used to be buried within the mpkg). Sassafras also confirmed that k2clientconfig tool itself "hasn't been modded in years… and [there are] no plans to change it." The current recipes and supporting Python script for K2 Client depend on the previous mpkg arrangement.

Further complicating matters, version 7.2 makes changes to the K2 server, so some might not choose to migrate from 7.1 immediately. It might make sense to leave the current version for those using 7.1.0.x and earlier and rewrite for 7.2 and later, fetching the flat pkg installer and k2clientconfig directly. We'd have to decide whether to do version control on k2clientconfig itself or just grab it once (for example, have the Python script check to see if it exists). Alternately, we could bring some scripting into play to grab either the mpkg version or the pkg version as appropriate, since in my preliminary testing I couldn't get k2clientconfig to modify the older flat pkg files (and the message from Sassafras suggests that their initial flat packages did not support modification in this way).

I've attempted to document what I've learned about where items are stored on Sassafras' server, including non-current versions (something that the existing recipes did not attempt to implement, although it wouldn't be difficult to add—I might just fork that). I did so through this recipe:

   https://gist.github.com/jazzace/8a415c85c60bda77dd74

This also creates an odd case where a download recipe does not generate a dmg or zip that contains the pkg; Sassafras lets you grab the pkg directly. Yet, we will almost certainly want to modify the pkg with k2clientconfig before deployment.

I'm not sure what is the best way to handle this moving forward, but I believe I have documented the situation for discussion purposes. I will experiment with some options myself, but I look forward to hearing what others suggest.

**Comment by jazzace** [comment]
Now that we have a 7.3.x.x, I recalled that omitting the version number entirely from the download URL will always pull the most current version. I've confirmed that this works for 7.3. We (by which I mean "Tim") should probably update the recipe's VERSION information to state that a null value for VERSION will pull the latest version. (It might make sense for that to be the default value as well.)

**Comment by timsutton** [comment]
Thanks, I'd forgotten that leaving VERSION empty had that effect. Updated the recipe with that, as well as bumped the default to `73`. Now that I think of it, perhaps it would make more sense at this point for `VERSION` to be defaulted to empty? New client versions are backwards-compatible with older server versions.
