### ISSUE TITLE
AdobeFlashPlayer.munki recipe fails

### ISSUE THREAD

**Issue by mohremail** [autopkg/recipes#68]
Since a few days ago every time autopkg runs I get the error below. I'm sorry if this is normal, I'm not used to using this completely yet, I've only had it up and running about 3-4 months now. But this is the first time I've seen these errors persist as long as I have, usually in a day or two they go away. 

Thank you, for everything you do to help the IT community and for your help on this issue.

Mike
The following recipes failed:
    AdobeFlashPlayer.munki
        Error in com.github.autopkg.munki.FlashPlayerNoRepackage: Processor: AdobeFlashDownloadDecoder: Error: Unexpected exception in running `security` command: `security` error: security: cert import failed: write permissions error
security: problem decoding
, return code: 1

**Comment by mohremail** [comment]
Sorry, will put this on the munki-dev group list... my bad...

**Comment by gregneagle** [comment]
There's no reason to put this on the munki-dev group list -- you are reporting an issue with an AutoPkg recipe.

On the other hand, there

**Comment by gregneagle** [comment]
See discussion of this issue on the autopkg-discuss list.

**Comment by timsutton** [comment]
Hopefully this has been addressed by https://github.com/autopkg/recipes/commit/657b2eb51f22dd14d44b90a0ae7a1d3e3313087e .

**Comment by timsutton** [comment]
A few people have confirmed it to be resolved - closing hopefully for the last time..
