### ISSUE TITLE
MSOffice2011UpdateInfoProvider.py 403 Error

### ISSUE THREAD

**Issue by sfrostick** [autopkg/recipes#73]
autopkg run -v MSOffice2011Updates.munki
     Processing MSOffice2011Updates.munki...
     MSOffice2011UpdateInfoProvider
            Can't download http://www.microsoft.com/mac/autoupdate/0409MSOf14.xml: HTTP Error 403: Forbidden
     Failed.
     Receipt written to ~/Library/AutoPkg/Cache/local.munki.MSOffice2011Updates/receipts   /MSOffice2011Updates-receipt-20150212-092125.plist

    The following recipes failed:
    MSOffice2011Updates.munki
    Error in local.munki.MSOffice2011Updates: Processor: MSOffice2011UpdateInfoProvider: Error: Can't download http://www.microsoft.com/mac/autoupdate/0409MSOf14.xml: HTTP Error 403: Forbidden

    Nothing downloaded, packaged or imported.

Seems that the MSOffice2011UpdateInfoProvider.py is now producing a 403 with the default user agent from urllib2, sightly modified example from line 192.

    import urllib2
    try:
         fref = urllib2.urlopen('http://www.microsoft.com/mac/autoupdate/0409MSOf14.xml')
         data = fref.read()
          fref.close()
    except BaseException as err:
       print err          

Produces: HTTP Error 403: Forbidden

However with a user agent set to Mozilla 5.10

    import urllib2
    try:
         fref = urllib2.Request('http://www.microsoft.com/mac/autoupdate/0409MSOf14.xml')
         fref.add_header('User-agent', 'Mozilla 5.10')
         res = urllib2.urlopen(fref)
         data = res.read()
         res.close()
    except BaseException as err:
         print err

This grabs the xml file successfully.

**Comment by timsutton** [comment]
Thanks! Looks like even an empty User-Agent works, but 'Python-urllib/2.7' returns the 403. Hrm...

**Comment by bochoven** [comment]
Same problem for the MSLync recipe

**Comment by timsutton** [comment]
And Outlook 15..

**Comment by sheagcraig** [comment]
I've had a number of Download pages fail to get served for the same reason (URLTextSearcher). Changing the user-agent gets you through.

**Comment by gregneagle** [comment]
This feels like Microsoft specifically tried to block AutoPkg; we may want to investigate what user agent is used by the Microsoft AutoUpdater itself.

**Comment by timsutton** [comment]
That's what I ended up doing - ran MAU through Charles and set the same User-Agent.

**Comment by gregneagle** [comment]
Ah, good. I had only seen the conversation, and wasn't sure what UserAgent you ended up using.
