### ISSUE TITLE
Handbrake.download.recipe

### ISSUE THREAD

**Issue by jleys1** [autopkg/recipes#77]
Seems like sparkle feed has not been updated yet...

Processing Handbrake.munki.recipe...
Couldn't download https://handbrake.fr/rotation.php?file=HandBrake-0.10.0
MacOSX.6_GUI_x86_64.dmg&update=true: HTTP Error 404: Not Found
Failed.

The following recipes failed:
    Handbrake.munki.recipe
        Error in local.munki.Handbrake: Processor: URLDownloader: Error: Couldn't download http://handbrake.fr/rotation.php?file=HandBrake-0.10.0-MacOSX.6_GUI_x86_64.dmg&update=true: HTTP Error 404: Not Found

Nothing downloaded, packaged or imported.

**Comment by timsutton** [comment]
It will be, eventually (see #76). Kind of silly that they removed the old download.

**Comment by timsutton** [comment]
Their feed has been updated.

**Comment by MichalMMac** [comment]
Looks like 0.10.2 is out.

SparkleUpdateInfoProvider: Found URL http://handbrake.fr/rotation.php?file=HandBrake-0.10.1-MacOSX.6_GUI_x86_64.dmg&update=true
URLDownloader
Couldn't download http://handbrake.fr/rotation.php?file=HandBrake-0.10.1-MacOSX.6_GUI_x86_64.dmg&update=true: HTTP Error 404: Not Found
Failed.

**Comment by timsutton** [comment]
From the 0.10.2 [release announcement](https://handbrake.fr/news.php?article=32):

"Please note that the built-in updater will be enabled at a later date to allow us to stagger the downloads."
