### ISSUE TITLE
munkitools.munki recipe uses Google Code instead of GitHub

### ISSUE THREAD

**Issue by flammable** [autopkg/recipes#79]
Hey guys -

I saw that Tim Sutton made some changes to the munkitools2.munki recipe recently - would it be possible to give similar attention to the munkitools.munki recipe?  It's still checking Google Code, so it's not pulling the recent security fix for Munki 1 (which was only posted to GitHub).

Thank you!

Mike

**Comment by gregneagle** [comment]
I'd really rather people _stop_ using the Munki 1 tools.

**Comment by flammable** [comment]
I completely understand that.

My intention is to manage as many computers as we might encounter on campus - and there have been a handful of 10.5 machines that can't run Munki 2.  I'd prefer to have them managed than not, while we find out how to go about replacing them.  That way, they're checking into MunkiReport, we have their serial number, and they're as current as they can be with software updates.

**Comment by timsutton** [comment]
I think if it's not currently pointing to the latest version, the munkitools.munki recipe should either be updated or be removed from the repo. There may well be not another Munki tools 1 update..

**Comment by gregneagle** [comment]
Certainly my intention is that there will never be another release of the Munki (1) tools. The recent security update was an exception that i hope won't need to be repeated.

**Comment by jessepeterson** [comment]
I'm sure folks have noticed but the recipe seems to be outright failing now. Tim's advice of either updating the recipe or removing it ought to be considered again. If it were to be updated I think this may be a candidate for the download: https://munkibuilds.org/munkitools-latest.dmg

**Comment by gregneagle** [comment]
I would accept a PR that removed it.

**Comment by timsutton** [comment]
Removed the munkitools 1 recipe and processors in https://github.com/autopkg/recipes/commit/4c36d2906abae86ac24258f7232aeb373848634f.
