### ISSUE TITLE
Java 8 importing as JavaAppletPlugin-%version%.pkg and not OracleJava8-%version%.pkg

### ISSUE THREAD

**Issue by Error-freeIT** [autopkg/recipes#80]
Hello Tim,

After running the OracleJava8.munki.recipe. I check my Munki pkgs directory to find "JavaAppletPlugin-1.8.40.27.pkg" and not the expected "OracleJava8-%version%.pkg" (ideally I would like to name it "java-%version%.pkg"). To me it looks like the PkgCopier in Oracle.Java8.pkg.recipe isn't renaming the extracted pkg.
![screen shot 2015-03-25 at 11 17 21 am](https://cloud.githubusercontent.com/assets/5794097/6816272/c34dae56-d2e0-11e4-8a67-cdeb82454567.png)

if you need more information, let me know.

I'm running AutoPkg version 0.4.2.

Thank you,
Michael

**Comment by timsutton** [comment]
Thanks. I'd argue it's not a significant issue that the Munki pkg file isn't set to the NAME in the recipe (or otherwise), as long as the pkginfo is - and so never even noticed this - but I might as well be more consistent while I'm at it.

**Comment by Error-freeIT** [comment]
Thanks for fixing this so fast. I really appreciate it.
