### ISSUE TITLE
VLC 2.2 recipe

### ISSUE THREAD

**Issue by morgrowe** [autopkg/recipes#81]
Really appreciate all the work that is put into making these recipes, however the VLC Media Player one doesn't appear to be downloading version 2.2. The last version it downloaded and imported into my Munki repo was 2.1.5. Any idea how to resolve this issue?

VLC's website: http://www.videolan.org/vlc/index.en_GB.html

Thanks!
Morgan

**Comment by timsutton** [comment]
Yes: contact VLC and ask them why the feed has still not been updated. Sometimes they are just being cautious or have other reasons.

**Comment by morgrowe** [comment]
Ok, I'll send them an email and let you know what they say.

**Comment by timsutton** [comment]
Also, what you can do in the meantime is to download it manually and pass the downloaded DMG to the recipe using the `--pkg` option for `autopkg run`.

**Comment by morgrowe** [comment]
Great, nice to know there's a workaround just in case!

**Comment by morgrowe** [comment]
Videolan said they will update the feed as soon as 2.2.1 is ready in case there are any problems with 2.2.0.

**Comment by timsutton** [comment]
Thanks for confirming! They have done something similar before when making major architectural changes and are aware of issues affecting certain hardware or OS combinations.
