### ISSUE TITLE
Recipe not honoring all overrides

### ISSUE THREAD

**Issue by hfike** [autopkg/recipes#83]
MSOffice2011Updates.munki is ignoring the NAME key and MUNKI_UPDATE_NAME key in recipe overrides.
I am overriding the NAME to "MicrosoftOffice2011Update", however, the name in the pkginfo generated is "Office2011_update".
I also tried overriding MUNKI_UPDATE_NAME, however, got the same exact result.

Gist of override: https://gist.github.com/hfike/57c751f67efff1e21727#file-office2011-update-override
Gist of pkginfo from override: https://gist.github.com/hfike/57c751f67efff1e21727#file-office2011-update-pkginfo
Autopkg run: https://gist.github.com/hfike/57c751f67efff1e21727#file-gistfile1-txt

**Comment by timsutton** [comment]
Should be fixed here: b1c3dbfd05aa131170683cd201f9f15f34c91e35

This was caused when the recipes were split up and a Process argument `munki_update_name` was left behind.

**Comment by hfike** [comment]
Yep, overriding NAME works as expected again. Thanks!
