### ISSUE TITLE
Dropbox pkg version issue ?

### ISSUE THREAD

**Issue by Thomgi** [autopkg/recipes#87]
Hi,

Since yesterday, each time autopkg runs on the Dropbox.pkg recipe I have a different version. It switch between 3.4.6 and 3.6.4 (formely 3.6.3) each time it runs.

If i'm right, version 3.4.6 is the last stable release, and 3.6.4 is the last beta one.

Is it normal ?

**Comment by timsutton** [comment]
I've seen these versions flip-flop in the past, which would just be a result of their server-side code or CDNs. There's no formal system by which Dropbox determines a latest version, it just grabs a URL from their main download page.

Also, my general recommendation has been that people not regularly import new Dropbox packages and instead let the client update itself.
