### ISSUE TITLE
Adium.download.recipe URL issue

### ISSUE THREAD

**Issue by n8felton** [autopkg/recipes#89]
```
$ autopkg run Adium.download.recipe -vvv
Processing Adium.download.recipe...
{'AUTOPKG_VERSION': u'0.4.0',
 u'BRANCH': u'release',
 u'MUNKI_REPO': u'/munki',
 u'NAME': u'Adium',
 'PARENT_RECIPES': [],
 'RECIPE_CACHE_DIR': u'/Users/itsadmin/Library/AutoPkg/Cache/com.github.autopkg.download.Adium',
 'RECIPE_DIR': u'/Users/itsadmin/Library/AutoPkg/RecipeRepos/com.github.autopkg.recipes/Adium',
 'RECIPE_OVERRIDE_DIRS': ['~/Library/AutoPkg/RecipeOverrides'],
 'RECIPE_PATH': u'/Users/itsadmin/Library/AutoPkg/RecipeRepos/com.github.autopkg.recipes/Adium/Adium.download.recipe',
 u'RECIPE_REPOS': {u'/Users/itsadmin/Library/AutoPkg/RecipeRepos/com.github.autopkg.arubdesu-recipes': {
    URL = "https://github.com/autopkg/arubdesu-recipes";
},
                   u'/Users/itsadmin/Library/AutoPkg/RecipeRepos/com.github.autopkg.autopkg': {
    URL = "https://github.com/autopkg/autopkg";
},
                   u'/Users/itsadmin/Library/AutoPkg/RecipeRepos/com.github.autopkg.bochoven-recipes': {
    URL = "https://github.com/autopkg/bochoven-recipes";
},
                   u'/Users/itsadmin/Library/AutoPkg/RecipeRepos/com.github.autopkg.cgerke-recipes': {
    URL = "https://github.com/autopkg/cgerke-recipes";
},
                   u'/Users/itsadmin/Library/AutoPkg/RecipeRepos/com.github.autopkg.dankeller-recipes': {
    URL = "https://github.com/autopkg/dankeller-recipes";
},
                   u'/Users/itsadmin/Library/AutoPkg/RecipeRepos/com.github.autopkg.derak-recipes': {
    URL = "https://github.com/autopkg/derak-recipes";
},
                   u'/Users/itsadmin/Library/AutoPkg/RecipeRepos/com.github.autopkg.gerardkok-recipes': {
    URL = "https://github.com/autopkg/gerardkok-recipes";
},
                   u'/Users/itsadmin/Library/AutoPkg/RecipeRepos/com.github.autopkg.groob-recipes': {
    URL = "https://github.com/autopkg/groob-recipes";
},
                   u'/Users/itsadmin/Library/AutoPkg/RecipeRepos/com.github.autopkg.hansen-m-recipes': {
    URL = "https://github.com/autopkg/hansen-m-recipes";
},
                   u'/Users/itsadmin/Library/AutoPkg/RecipeRepos/com.github.autopkg.hjuutilainen-recipes': {
    URL = "https://github.com/autopkg/hjuutilainen-recipes";
},
                   u'/Users/itsadmin/Library/AutoPkg/RecipeRepos/com.github.autopkg.jaharmi-recipes': {
    URL = "https://github.com/autopkg/jaharmi-recipes";
},
                   u'/Users/itsadmin/Library/AutoPkg/RecipeRepos/com.github.autopkg.jazzace-recipes': {
    URL = "https://github.com/autopkg/jazzace-recipes";
},
                   u'/Users/itsadmin/Library/AutoPkg/RecipeRepos/com.github.autopkg.jessepeterson-recipes': {
    URL = "https://github.com/autopkg/jessepeterson-recipes";
},
                   u'/Users/itsadmin/Library/AutoPkg/RecipeRepos/com.github.autopkg.jleggat-recipes': {
    URL = "https://github.com/autopkg/jleggat-recipes";
},
                   u'/Users/itsadmin/Library/AutoPkg/RecipeRepos/com.github.autopkg.joshua-d-miller-recipes': {
    URL = "https://github.com/autopkg/joshua-d-miller-recipes";
},
                   u'/Users/itsadmin/Library/AutoPkg/RecipeRepos/com.github.autopkg.jps3-recipes': {
    URL = "https://github.com/autopkg/jps3-recipes";
},
                   u'/Users/itsadmin/Library/AutoPkg/RecipeRepos/com.github.autopkg.justinrummel-recipes': {
    URL = "https://github.com/autopkg/justinrummel-recipes";
},
                   u'/Users/itsadmin/Library/AutoPkg/RecipeRepos/com.github.autopkg.keeleysam-recipes': {
    URL = "https://github.com/autopkg/keeleysam-recipes";
},
                   u'/Users/itsadmin/Library/AutoPkg/RecipeRepos/com.github.autopkg.lashomb-recipes': {
    URL = "https://github.com/autopkg/lashomb-recipes";
},
                   u'/Users/itsadmin/Library/AutoPkg/RecipeRepos/com.github.autopkg.luisgiraldo-recipes': {
    URL = "https://github.com/autopkg/luisgiraldo-recipes";
},
                   u'/Users/itsadmin/Library/AutoPkg/RecipeRepos/com.github.autopkg.mosen-recipes': {
    URL = "https://github.com/autopkg/mosen-recipes";
},
                   u'/Users/itsadmin/Library/AutoPkg/RecipeRepos/com.github.autopkg.n8felton-recipes': {
    URL = "https://github.com/autopkg/n8felton-recipes";
},
                   u'/Users/itsadmin/Library/AutoPkg/RecipeRepos/com.github.autopkg.nmcspadden-recipes': {
    URL = "https://github.com/autopkg/nmcspadden-recipes";
},
                   u'/Users/itsadmin/Library/AutoPkg/RecipeRepos/com.github.autopkg.recipes': {
    URL = "https://github.com/autopkg/recipes";
},
                   u'/Users/itsadmin/Library/AutoPkg/RecipeRepos/com.github.autopkg.rustymyers-recipes': {
    URL = "https://github.com/autopkg/rustymyers-recipes";
},
                   u'/Users/itsadmin/Library/AutoPkg/RecipeRepos/com.github.autopkg.scriptingosx-recipes': {
    URL = "https://github.com/autopkg/scriptingosx-recipes";
},
                   u'/Users/itsadmin/Library/AutoPkg/RecipeRepos/com.github.autopkg.sheagcraig-recipes': {
    URL = "https://github.com/autopkg/sheagcraig-recipes";
},
                   u'/Users/itsadmin/Library/AutoPkg/RecipeRepos/com.github.autopkg.swy-recipes': {
    URL = "https://github.com/autopkg/swy-recipes";
},
                   u'/Users/itsadmin/Library/AutoPkg/RecipeRepos/com.github.autopkg.thenikola-recipes': {
    URL = "https://github.com/autopkg/thenikola-recipes";
},
                   u'/Users/itsadmin/Library/AutoPkg/RecipeRepos/com.github.autopkg.timsutton-recipes': {
    URL = "https://github.com/autopkg/timsutton-recipes";
}},
 u'RECIPE_SEARCH_DIRS': [u'.',
                         u'~/Library/AutoPkg/Recipes',
                         u'/Library/AutoPkg/Recipes',
                         u'/Users/itsadmin/Library/AutoPkg/RecipeRepos/com.github.autopkg.recipes',
                         u'/Users/itsadmin/Library/AutoPkg/RecipeRepos/com.github.autopkg.autopkg',
                         u'/Users/itsadmin/Library/AutoPkg/RecipeRepos/com.github.autopkg.timsutton-recipes',
                         u'/Users/itsadmin/Library/AutoPkg/RecipeRepos/com.github.autopkg.keeleysam-recipes',
                         u'/Users/itsadmin/Library/AutoPkg/RecipeRepos/com.github.autopkg.nmcspadden-recipes',
                         u'/Users/itsadmin/Library/AutoPkg/RecipeRepos/com.github.autopkg.gerardkok-recipes',
                         u'/Users/itsadmin/Library/AutoPkg/RecipeRepos/com.github.autopkg.hjuutilainen-recipes',
                         u'/Users/itsadmin/Library/AutoPkg/RecipeRepos/com.github.autopkg.jessepeterson-recipes',
                         u'/Users/itsadmin/Library/AutoPkg/RecipeRepos/com.github.autopkg.derak-recipes',
                         u'/Users/itsadmin/Library/AutoPkg/RecipeRepos/com.github.autopkg.dankeller-recipes',
                         u'/Users/itsadmin/Library/AutoPkg/RecipeRepos/com.github.autopkg.hansen-m-recipes',
                         u'/Users/itsadmin/Library/AutoPkg/RecipeRepos/com.github.autopkg.jleggat-recipes',
                         u'/Users/itsadmin/Library/AutoPkg/RecipeRepos/com.github.autopkg.sheagcraig-recipes',
                         u'/Users/itsadmin/Library/AutoPkg/RecipeRepos/com.github.autopkg.jaharmi-recipes',
                         u'/Users/itsadmin/Library/AutoPkg/RecipeRepos/com.github.autopkg.swy-recipes',
                         u'/Users/itsadmin/Library/AutoPkg/RecipeRepos/com.github.autopkg.lashomb-recipes',
                         u'/Users/itsadmin/Library/AutoPkg/RecipeRepos/com.github.autopkg.rustymyers-recipes',
                         u'/Users/itsadmin/Library/AutoPkg/RecipeRepos/com.github.autopkg.joshua-d-miller-recipes',
                         u'/Users/itsadmin/Library/AutoPkg/RecipeRepos/com.github.autopkg.arubdesu-recipes',
                         u'/Users/itsadmin/Library/AutoPkg/RecipeRepos/com.github.autopkg.jps3-recipes',
                         u'/Users/itsadmin/Library/AutoPkg/RecipeRepos/com.github.autopkg.scriptingosx-recipes',
                         u'/Users/itsadmin/Library/AutoPkg/RecipeRepos/com.github.autopkg.n8felton-recipes',
                         u'/Users/itsadmin/Library/AutoPkg/RecipeRepos/com.github.autopkg.luisgiraldo-recipes',
                         u'/Users/itsadmin/Library/AutoPkg/RecipeRepos/com.github.autopkg.justinrummel-recipes',
                         u'/Users/itsadmin/Library/AutoPkg/RecipeRepos/com.github.autopkg.groob-recipes',
                         u'/Users/itsadmin/Library/AutoPkg/RecipeRepos/com.github.autopkg.jazzace-recipes',
                         u'/Users/itsadmin/Library/AutoPkg/RecipeRepos/com.github.autopkg.thenikola-recipes',
                         u'/Users/itsadmin/Library/AutoPkg/RecipeRepos/com.github.autopkg.mosen-recipes',
                         u'/Users/itsadmin/Library/AutoPkg/RecipeRepos/com.github.autopkg.bochoven-recipes',
                         u'/Users/itsadmin/Library/AutoPkg/RecipeRepos/com.github.autopkg.cgerke-recipes'],
 'verbose': 3}
SparkleUpdateInfoProvider
{'Input': {'appcast_query_pairs': {
    generation = 2;
    type = release;
},
           'appcast_url': u'http://www.adium.im/sparkle/update.php'}}
Can't open URL http://www.adium.im/sparkle/update.php?generation=2&type=release
Failed.
Receipt written to /Users/itsadmin/Library/AutoPkg/Cache/com.github.autopkg.download.Adium/receipts/Adium.download-receipt-20150624-094106.plist

The following recipes failed:
    Adium.download.recipe
        Error in com.github.autopkg.download.Adium: Processor: SparkleUpdateInfoProvider: Error: Can't open URL http://www.adium.im/sparkle/update.php?generation=2&type=release

Nothing downloaded, packaged or imported.
```

**Comment by timsutton** [comment]
This Sparkle URL now redirects to an HTTPS URL (https://www.adium.im/sparkle/update.php?generation=2&type=release) that seems like Python's urllib2 may have troubles negotiating. I can use cURL or Python's requests on OS X successfully. But with urllib2:

On OS X 10.10, Python 2.7.6:
```python
URLError: <urlopen error [Errno 8] _ssl.c:507: EOF occurred in violation of protocol>
```

On Debian, Python 2.7.9:
```python
urllib2.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581)>
```

**Comment by fuzzylogiq** [comment]
Looks like the server is forcing TLS1+:

    $ openssl s_client -connect www.adium.im:443
    CONNECTED(00000003)
    4371:error:140790E5:SSL routines:SSL23_WRITE:ssl handshake failure:/SourceCache/OpenSSL098/OpenSSL098-52.30.1/src/ssl/s23_lib.c:185
    $ openssl s_client -tls1 -connect www.adium.im:443
    CONNECTED(00000003)
    depth=1 /C=GB/ST=Greater Manchester/L=Salford/O=COMODO CA Limited/CN=COMODO RSA Domain Validation Secure Server CA
    <snip>

Think it's pretty difficult to force that in urllib2 without overriding various parts of it.

**Comment by n8felton** [comment]
https://www.ssllabs.com/ssltest/analyze.html?d=adium.im

Looks like they are only allowing TLSv1 with a very narrow selection of supported cipher suites.

**Comment by ChrisForsythe** [comment]
So force urllib2 to use tls1+?

http://anotherlayer.net/2014/10/16/forcing-tls1-in-pythons-urllib2-on-osx/

Or use ssl.wrap_socket() ?

http://stackoverflow.com/questions/22657498/i-want-to-choose-the-transport-layer-security-protocol-in-urllib2

Just some googling but maybe that will help

**Comment by bochoven** [comment]
We could just *ask* if they can change their server, maybe it's just misconfigured

**Comment by ChrisForsythe** [comment]
What ciphers did you want?

**Comment by n8felton** [comment]
@bochoven I have thought about doing that. Are you volunteering? haha

@ChrisForsythe I personally have no preference, just whatever the library can handle, but I often point my configurations to https://wiki.mozilla.org/Security/Server_Side_TLS#Recommended_configurations or https://cipherli.st/

**Comment by timsutton** [comment]
As time goes on, more servers will be using whatever mechanisms are available to ensure TLS is negotiated, and the situation with urllib2, SSL and Python 2.7 on OS X will continue to be broken for a long time. There's already a precedent of some recipes needing to use various workarounds for issues with particular server SSL configurations.

The download recipe could possibly be rewritten to use some other website/mirror that doesn't exhibit this issue - at least Adium is very rarely updated.

I think a better long-term solution would be for AutoPkg to look at incorporating some of the code Greg has already written (and has been stable in Munki for a number of months) that instead uses Apple's own APIs for HTTP traffic. This wouldn't live in URLDownloader, but instead provide a few functions that other processors (like URLDownloader, Sparkle, etc.) could use as an alternative to urllib/urllib2 for anything to do with HTTP(S).

**Comment by gregneagle** [comment]
"I think a better long-term solution would be for AutoPkg to look at incorporating some of the code Greg has already written (and has been stable in Munki for a number of months) that instead uses Apple's own APIs for HTTP traffic."

Two reactions to this:
1) This would really throw a wrench at the people trying to get AutoPkg running usefully on Windows.

2) I worry about what Apple is doing with Application Transport Security -- they could easily make the NSURL APIs essentially useless from Python.

**Comment by timsutton** [comment]
Good point with (1), hadn't thought of that. Though NSURL needn't be the _only_ method supported - it could be possible for AutoPkg to pick different HTTP modules depending on the platform. For (2), it definitely seems like there's dust to settle in the Beta period. The output from CFNetwork when NSURL APIs are used from Python on the current 10.11 leaves itself open to interpretation...

**Comment by timsutton** [comment]
For reference, filed rdar://21652505, which references rdar://21144215.

**Comment by sts** [comment]
Anyone knows what would be the recommended cipher suites which are still supported by OSX/Python 2.7/urllib?

**Comment by laapsaap** [comment]
So why not just grab latest download url from -> http://sourceforge.net/projects/adium/files/latest/download ?

**Comment by timsutton** [comment]
That's a possibility. If anyone feels like submitting the necessary changes to the recipe before I get a chance to try this, feel free!

Adium is updated so rarely (and probably not so widely used, anymore) that I don't think admins have been too motivated to get this recipe working again.

**Comment by n8felton** [comment]
FWIW, I'd rather not support any downloads from SourceForce.

**Comment by timsutton** [comment]
I don't have a personal bias if the bits in the DMG are the same.

Greg yesterday posted a CURLDownloader processor for testing: https://github.com/autopkg/autopkg/blob/ecd05590964b7c0adebd12d204895fa5ba42da1d/Code/autopkglib/CURLDownloader.py

The recipe uses a Sparkle feed for checking updates, however, so the suggestion of scraping the SF URL is still a much simpler solution..

**Comment by n8felton** [comment]
I was going to attempt to poke at this a bit, but I noticed that http://sourceforge.net/projects/adium/files/latest/download points to ```AdiumX_Source_0.89.tgz``` which certainly isn't what we're looking for.

**Comment by ChrisForsythe** [comment]
We moved Adium off of sourceforge a long while ago. 



—
Chris Forsythe

**Comment by passitor** [comment]
Has this issue been resolved yet?

**Comment by ChrisForsythe** [comment]
No one as of yet has stated exactly which cipher is necessary. Someone mentioned adding more support to autopkg but then someone else mentioned it breaking windows. Which seems odd since you can check for a platform before building something out.


So again, as I asked months ago, what **exactly** needs to be done to support this?

Are you suggesting enabling sslv3? That seems rather backwards if so since ssl is on the decline.

Are you suggesting bumping tls to 1.2? I would agree with this.

If not the two above, then what? It would be nice to get a succinct, clear answer as to how to resolve this problem immediately and then permanently.

**Comment by gregneagle** [comment]
@ChrisForsythe : what is the preferred URL for the current version of Adium?

**Comment by ChrisForsythe** [comment]
@gregneagle https://adium.im as far as I'm aware. I used to be the project manager and wanted to get the whole solution and send it over to the adium devs if there is any action they needed to take.

**Comment by gregneagle** [comment]
That's a web page and not a download link, but it's a start, thanks. I don't think there is any action the Adium devs need to take.

**Comment by ChrisForsythe** [comment]
@gregneagle Your question was a bit ambiguous then. :)

Can what you're working with parse xml?

**Comment by gregneagle** [comment]
It was asked within the context of this project, so not as ambiguous as you might think.

Yes, we can parse XML and do grep searches through HTML source to find download links. We'd rather, however, have a clear download URL for $PRODUCT_LATEST, but it's not required.

**Comment by gregneagle** [comment]
The current download recipe is using what appears to be an abandoned/outdated sparkle feed:
```
$ curl https://www.adium.im/sparkle/update.php
<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0" xmlns:sparkle="http://www.andymatuschak.org/xml-namespaces/sparkle">
  <channel>
    <title>Adium Updates</title>
    <language>en</language>
    <item>
        <title>Adium 1.1.4</title>
        <pubDate>Monday, November 5th, 2007 20:00:00 GMT-5</pubDate>
        <sparkle:releaseNotesLink>https://www.adium.im/changelogs/1.1.4.html</sparkle:releaseNotesLink> 
        <enclosure sparkle:md5Sum="a3013db6c56a8bd249191ced6d749b30" sparkle:version="1.1.4" url="http://adiumx.cachefly.net/Adium_1.1.4.dmg" length="16463533" type="application/octet-stream"/>
    </item>
  </channel>
</rss>
```

whereas the adium.im web page links to a newer version: 
```html
<a href="https://adiumx.cachefly.net/Adium_1.5.10.2.dmg"><span class="downloadlink">Download Adium 1.5.10.2</span></a>
```

**Comment by gregneagle** [comment]
@ChrisForsythe: Current Adium download still references that same Sparkle URL:
```xml
	<key>SUFeedURL</key>
	<string>https://www.adium.im/sparkle/update.php</string>
```
so I'm guessing just scraping the download URL from the page returned from https://adium.im will have to do.

**Comment by gregneagle** [comment]
Addressed here: https://github.com/autopkg/recipes/commit/e3c60043a6769f9006ec0c10a242bbb24a5ac4a4

**Comment by passitor** [comment]
I'm getting an error using the new recipe:

    Adium.munki
        Error in local.munki.Adium: Processor: URLTextSearcher: Error: Could not retrieve URL: https://adium.im

From the same machine, I can reach the URL with no problem, so maybe this is still some sort of urllib2 error?

    $ curl -I https://adium.im
    HTTP/1.1 200 OK
    Date: Thu, 05 May 2016 22:55:24 GMT
    Server: Apache
    Strict-Transport-Security: max-age=2628000
    X-Powered-By: PHP/5.4.42
    Vary: User-Agent
    Content-Type: text/html

**Comment by gregneagle** [comment]
What version of autopkg are you using? Works here with the current version, which uses `curl` and not urllib2 in URLTextSearcher.

```
% autopkg version
0.6.1
```

**Comment by passitor** [comment]
Yes, I was on an old version. Upgraded and it works fine. Thank you!
