### ISSUE TITLE
AdobeAcrobatProUpdate recipe failing to download

### ISSUE THREAD

**Issue by hfike** [autopkg/recipes#94]
Running autopkg run AdobeAcrobatUpdate.download fails to download:

autopkg run AdobeAcrobatProXUpdate.download
Processing AdobeAcrobatProXUpdate.download...
Can't read response from URL https://armmf.adobe.com/arm-manifests/mac/10/10.1.15/{OS_VER_MAJ}.{OS_VER_MIN}/com_adobe_Acrobat_Pro_univ.plist: HTTP Error 404: Not Found
Failed.

The following recipes failed:
    AdobeAcrobatProXUpdate.download
        Error in com.github.autopkg.download.AdobeAcrobatProXUpdate: Processor: AdobeAcrobatProUpdateInfoProvider: Error: Can't read response from URL https://armmf.adobe.com/arm-manifests/mac/10/10.1.15/{OS_VER_MAJ}.{OS_VER_MIN}/com_adobe_Acrobat_Pro_univ.plist: HTTP Error 404: Not Found

Nothing downloaded, packaged or imported.

Tested on multiple OS versions by multiple users.

Potentially this file has changed: https://armmf.adobe.com/arm-manifests/mac/11/manifest_url_template.txt

See IRC for quick discussion: https://botbot.me/freenode/osx-server/2015-07-14/?msg=44531626&page=11 until https://botbot.me/freenode/osx-server/2015-07-14/?msg=44533328&page=11

**Comment by timsutton** [comment]
Thanks. I noticed the error today as well but thought it might just be transient. I will take a look soon.

It would be useful to know whether an old version of Pro X or XI still gets offered a current update if the recipe still fails.

**Comment by fuzzylogiq** [comment]
I can see why this is happening. Adobe have added an OS version to their URLs - the latest update (and future ones?) is only available to 10.8+, 10.6-7 are still pointed to the previous one, (though the older versions are also still hanging around with the older URL template format.) I think an input variable for the target OS needs to be added and some logic to pass the version number required and if it's >= the current one, to use the new URL template. I can do a PR if you'd like.

**Comment by timsutton** [comment]
That would be great. Seems plausible that back when I originally wrote the processor, I ignored the client OS parameter when it seemed to not make a difference.

If you have an Input variable for the checked OS version, it would be good to also let the processor fall back to a default of 10.8 so that the recipe works even without the Input var set.

I wonder whether the update actually _installs_ on older OSes, though I agree it would be good to follow whatever the feed does and merge in a minimum_os_version pkginfo key.

**Comment by hfike** [comment]
This is now working on both a 10.8 and a 10.10 autopkg instance.
