### ISSUE TITLE
TextWrangler: HTTP Error 404: Not Found

### ISSUE THREAD

**Issue by bahhhhh** [autopkg/recipes#99]
I get the following error when running run --recipe-list.
![screen_shot_2015-08-05_at_3 30 40_pm](https://cloud.githubusercontent.com/assets/4534172/9096644/602b3482-3b8c-11e5-907f-28d9f3ae20f9.png)

Might be a temporary issue with BareBones?

**Comment by timsutton** [comment]
Likely. This happened to me a few days ago and it resolved itself within a day. (And this has happened a couple other times with the BB updater).

**Comment by gregneagle** [comment]
Earlier today I was getting this:
```
The following recipes failed:
    TextWrangler.munki
        Error in com.disneyanimation.autopkg.munki.textwrangler: Processor: BarebonesURLProvider: Error: Unexpected error retrieving product manifest: '<urlopen error [Errno 8] _ssl.c:507: EOF occurred in violation of protocol>'
```

and now I'm getting this:

```
The following recipes failed:
    TextWrangler.munki
        Error in com.disneyanimation.autopkg.munki.textwrangler: Processor: BarebonesURLProvider: Error: Unexpected error retrieving product manifest: 'HTTP Error 404: Not Found'
```

so I think we probably need to just wait and see how things settle down.

**Comment by bahhhhh** [comment]
Thanks, guys!
